---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam' 
summary: Conozca los cambios más recientes en los servicios en la nube que forman parte de la plataforma BlueXP. 
---
= Cambios recientes en BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Conozca los cambios más recientes en los servicios en la nube que forman parte de la plataforma BlueXP. Para obtener un historial de versiones completo, vaya a link:release-notes-index.html["conjunto completo de notas de la versión"] por cada servicio individual.



== Funciones administrativas

En esta sección se describen las nuevas funciones relacionadas con las funciones de administración de BlueXP: Cuentas, conectores, credenciales de proveedores de nube y mucho más.



=== 14 de abril de 2025



==== Conector 3.9.51

Esta versión de BlueXP Connector incluye mejoras de seguridad y correcciones de errores menores.

En este momento, la versión 3.9.51 está disponible para modo estándar y modo restringido.



==== Gestión de acceso e identidades (IAM) de BlueXP

* Los usuarios sin el administrador de la organización o la carpeta o el administrador del proyecto deben tener asignada una función de protección contra ransomware para tener acceso a la protección contra ransomware. Puede asignar al usuario uno de estos dos roles: Administrador de protección contra ransomware o visor de protección contra ransomware.
* Los usuarios sin el administrador de la organización, la carpeta o el administrador del proyecto deben tener asignada una función de Keystone para tener acceso a Keystone. Se puede asignar a un usuario uno de estos dos roles: Administrador de Keystone o visor de Keystone.
+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso."^]

* Si tiene la función de administrador de organización o de carpeta o de administrador de proyecto, ahora puede asociar una suscripción de Keystone a un proyecto de IAM. La asociación de una suscripción de Keystone con un proyecto de IAM le permite controlar el acceso a Keystone dentro de BlueXP .




=== 28 de marzo de 2025



==== Versión en modo privado (3,9.50)

Ya está disponible una nueva versión de modo privado para descargar desde el https://mysupport.netapp.com/site/downloads["Sitio de soporte de NetApp"^]

La versión 3.9.50 incluye actualizaciones de los siguientes componentes y servicios de BlueXP .

[cols="3*"]
|===
| Componente o servicio | Versión incluida en esta versión | Cambios desde la versión anterior del modo privado 


| Conector | 3,9.50, 3.9.49 | Vaya a https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["Novedades en la página de conectores de BlueXP"] y consulte los cambios incluidos para las versiones 3.9.50 y 3,9.49. 


| Backup y recuperación | 17 de marzo de 2025 | Vaya a https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["Novedades en la página de backup y recuperación de BlueXP"^] y consulte los cambios incluidos en la versión de marzo de 2024. 


| Clasificación | 10 de marzo de 2025 (versión 1,41) | Vaya a https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["Novedades en la página de clasificación de BlueXP"^] y consulte los cambios incluidos en las versiones de 1,38 a 1.371.41. 
|===
Para obtener más información sobre el modo privado, incluido el modo de actualización, consulte lo siguiente:

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Aprende sobre el modo privado"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Descubre cómo empezar a utilizar BlueXP en modo privado"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["Aprenda a actualizar el conector cuando use el modo privado"]




=== 10 de marzo de 2025



==== Conector 3.9.50

Esta versión de BlueXP Connector incluye mejoras de seguridad y correcciones de errores menores.

En este momento, la versión 3.9.50 está disponible para modo estándar y modo restringido.



==== Versión beta de NetApp Keystone disponible en BlueXP

NetApp Keystone pronto estará disponible a través de BlueXP  y ya se encontrará en fase beta. Puede acceder a la página de registro de la versión beta de NetApp Keystone desde la barra de navegación izquierda de BlueXP .



== Alertas



=== 7 de octubre de 2024



==== La página de lista de alertas de BlueXP

Usted puede identificar rápidamente clústeres de ONTAP con poca capacidad o bajo rendimiento, medir el grado de la disponibilidad e identificar los riesgos de seguridad. Es posible ver alertas relacionadas con la capacidad, el rendimiento, la protección, la disponibilidad, la seguridad y la configuración.



==== Detalles de alertas

Puede profundizar en los detalles de alertas y buscar recomendaciones.



==== Ver los detalles del clúster vinculados a ONTAP System Manager

Con las alertas de BlueXP , puede ver las alertas asociadas con su entorno de almacenamiento de ONTAP y obtener detalles vinculados a System Manager de ONTAP.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["Más información sobre las alertas de BlueXP"].



== Amazon FSX para ONTAP



=== 30 de marzo de 2025



==== iam:SimulatePermissionPolicy actualización de permisos

Ahora puede administrar `iam:SimulatePrincipalPolicy` el permiso desde la consola de BlueXP  cuando agrega credenciales de cuenta de AWS adicionales o agrega una nueva capacidad de carga de trabajo, como la carga de trabajo de GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Log de cambios de referencia de permisos"^]



=== 02 de marzo de 2025



==== Eventos de CloudShell en Tracker

Cada vez que utilice CloudShell para ejecutar operaciones de FSx para ONTAP desde cargas de trabajo de BlueXP , los eventos aparecen en Tracker.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["Aprende a supervisar y hacer un seguimiento de las operaciones de FSx para ONTAP en BlueXP"^]



=== 02 de febrero de 2025



==== Asocie FSX para el sistema de archivos ONTAP a un espacio de trabajo en BlueXP

Después de la integración de BlueXP  en noviembre de 2024, los sistemas de archivos FSx para ONTAP recién creados no se asociaron a un espacio de trabajo en BlueXP . Ahora, cuando creas o detectas sistemas de archivos FSx for ONTAP, estos se asocian a un espacio de trabajo dentro de una cuenta de BlueXP .

Si ya tienes sistemas de archivos FSx para ONTAP que no están asociados a un espacio de trabajo, te ayudaremos a asociarlos a un espacio de trabajo en BlueXP . link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-get-help.html#create-a-case-with-netapp-support["Cree un caso con el soporte de NetApp"^]Puede hacerlo desde la consola de BlueXP . Seleccione *Workload Factory* como servicio.



==== Eliminación del sistema de archivos del lienzo de BlueXP

Ahora puede eliminar un sistema de archivos FSx para ONTAP de un espacio de trabajo en el lienzo de BlueXP . Esta operación disocia el sistema de archivos de un espacio de trabajo para que pueda asociarlo a otro espacio de trabajo dentro de la misma cuenta de BlueXP .

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-remove-filesystem.html["Aprende a eliminar un sistema de archivos FSx para ONTAP de un espacio de trabajo en BlueXP"^]



==== Rastreador disponible para operaciones de monitoreo y seguimiento

Tracker, una nueva funcionalidad de supervisión, está disponible en Amazon FSx para NetApp ONTAP de BlueXP . Puede utilizar Tracker para supervisar y realizar un seguimiento del progreso y el estado de las credenciales, el almacenamiento y las operaciones de enlace, revisar detalles de tareas de operación y subtareas, diagnosticar cualquier problema o fallo, editar parámetros para operaciones fallidas y volver a intentar operaciones fallidas.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["Aprende a supervisar y hacer un seguimiento de las operaciones de FSx para ONTAP en BlueXP"^]



==== CloudShell disponible en cargas de trabajo de BlueXP

CloudShell está disponible cuando estás en cargas de trabajo de BlueXP  dentro de la consola de BlueXP . CloudShell le permite usar las credenciales de AWS y ONTAP que ha proporcionado en su cuenta de BlueXP  y ejecutar comandos de la CLI de AWS o comandos de la CLI de ONTAP en un entorno similar al shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Usar CloudShell"^]



== Almacenamiento Amazon S3



=== 5 de marzo de 2023



==== Posibilidad de añadir nuevos cubos desde BlueXP

Has tenido la posibilidad de ver cubos de Amazon S3 en BlueXP Canvas durante mucho tiempo. Ahora puede agregar nuevos cubos y cambiar las propiedades de los cubos existentes directamente desde BlueXP . https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["Descubra cómo añadir nuevos bloques de Amazon S3"].



== Almacenamiento de Azure Blob



=== 5 de junio de 2023



==== Capacidad de añadir nuevas cuentas de almacenamiento desde BlueXP

Has tenido la capacidad de ver Azure Blob Storage en BlueXP Canvas durante bastante tiempo. Ahora puede añadir nuevas cuentas de almacenamiento y cambiar las propiedades de las cuentas de almacenamiento existentes directamente desde BlueXP . https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["Descubre cómo añadir nuevas cuentas de almacenamiento de Azure Blob"].



== Azure NetApp Files



=== 13 de enero de 2025



==== Las funciones de red ahora son compatibles con BlueXP

Al configurar un volumen en Azure NetApp Files desde BlueXP , ahora se pueden indicar las funciones de red. Se alinea con la funcionalidad disponible en la Azure NetApp Files nativa.



=== 12 de junio de 2024



==== Se requiere un nuevo permiso

Ahora se necesita el siguiente permiso para gestionar Azure NetApp Files Volumes desde BlueXP:

Microsoft.Network/virtualNetworks/subnets/read

Se necesita este permiso para leer una subred de red virtual.

Si actualmente está gestionando Azure NetApp Files desde BlueXP, debe añadir este permiso al rol personalizado asociado a la aplicación Microsoft Entra que creó anteriormente.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["Aprenda a configurar una aplicación de Microsoft Entra y ver los permisos de rol personalizados"].



=== 22 de abril de 2024



==== Ya no se admiten plantillas de volumen

Ya no puede crear un volumen a partir de una plantilla. Esta acción se asoció con el servicio de corrección de BlueXP, que ya no está disponible.



== Backup y recuperación



=== 17 de marzo de 2025

Esta versión de copia de seguridad y recuperación de BlueXP  incluye las siguientes actualizaciones.



==== Exploración de instantáneas de SMB

Esta actualización de copia de seguridad y recuperación de BlueXP  resolvió un problema que impedía que los clientes examinaran las instantáneas locales en un entorno SMB.



==== Actualización del entorno de AWS GovCloud

Esta actualización de copia de seguridad y recuperación de BlueXP  solucionó un problema que impedía que la interfaz de usuario se conectara a un entorno de AWS GovCloud debido a errores de certificado TLS. El problema se resolvió mediante el nombre de host del conector BlueXP  en lugar de la dirección IP.



==== Límites de retención de política de backup

Anteriormente, la interfaz de usuario de backup y recuperación de BlueXP  limitaba los backups a 999 copias, mientras que la CLI permitía más. Ahora puede conectar hasta 4.000 volúmenes a una política de backup e incluir 1.018 volúmenes no adjuntos a una política de backup. Esta actualización incluye validaciones adicionales que evitan superar estos límites.



==== Resincronización de cloud de SnapMirror

Esta actualización garantiza que la resincronización de cloud de SnapMirror no se pueda iniciar desde el backup y la recuperación de BlueXP  para versiones de ONTAP no compatibles después de eliminar una relación de SnapMirror.



=== 21 de febrero de 2025

Esta versión de copia de seguridad y recuperación de BlueXP  incluye las siguientes actualizaciones.



==== Indización de alto rendimiento

Las funciones de backup y recuperación de datos de BlueXP  presentan una función de indexación actualizada que hace que la indexación de datos en el entorno de trabajo de origen sea más eficiente. La nueva función de indexación incluye actualizaciones en la interfaz de usuario, rendimiento mejorado del método de búsqueda y restauración de datos, actualizaciones a las funciones de búsqueda global y una mejor escalabilidad.

He aquí un desglose de las mejoras:

* *Consolidación de carpetas*: La versión actualizada agrupa carpetas usando nombres que incluyen identificadores específicos, lo que hace que el proceso de indexación sea más fluido.
* *Compactación de archivos de parquet*: La versión actualizada reduce el número de archivos utilizados para indexar cada volumen, simplificando el proceso y eliminando la necesidad de una base de datos adicional.
* *Escalar con más sesiones*: La nueva versión agrega más sesiones para manejar las tareas de indexación, acelerando el proceso.
* *Soporte para múltiples contenedores de índice*: La nueva versión utiliza múltiples contenedores para administrar y distribuir mejor las tareas de indexación.
* *Flujo de trabajo de índice dividido*: La nueva versión divide el proceso de indexación en dos partes, mejorando la eficiencia.
* *Concurrency mejorada*: La nueva versión permite eliminar o mover directorios al mismo tiempo, acelerando el proceso de indexación.


.¿Quién se beneficia de esta función?
La nueva función de indexación está disponible para todos los nuevos clientes.

.¿Cómo se habilita la indexación?
Para poder utilizar el método de búsqueda y restauración de datos, debe activar la indexación en cada entorno de trabajo de origen desde el que tiene pensado restaurar volúmenes o archivos. Esto permite que el catálogo indexado realice un seguimiento de cada volumen y cada archivo de copia de seguridad, haciendo que sus búsquedas sean rápidas y eficientes.

Active la indexación en el entorno de trabajo de origen seleccionando la opción Activar indexación al realizar una búsqueda y restauración.

Para obtener más información, consulte la documentación https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["Cómo restaurar los datos de ONTAP con la opción de  Restaurar"].

.Escala admitida
La nueva función de indexación admite lo siguiente:

* Eficacia de la búsqueda global en menos de 3 minutos
* Hasta 5 millones de archivos
* Hasta 5000 volúmenes por clúster
* Hasta 100K snapshots por volumen
* El tiempo máximo para la indexación de línea base es inferior a 7 días. El tiempo real variará según tu entorno.




==== Mejoras en el rendimiento de las búsquedas globales

Esta versión también incluye mejoras en el rendimiento de las búsquedas globales. Ahora verá indicadores de progreso y resultados de búsqueda más detallados, incluido el recuento de archivos y el tiempo necesario para la búsqueda. Los contenedores dedicados de búsqueda e indexación garantizan que las búsquedas globales se completen en menos de cinco minutos.

Tenga en cuenta estas consideraciones relacionadas con la búsqueda global:

* El nuevo índice no se realiza en instantáneas etiquetadas como hora.
* La nueva función de indexación sólo funciona en instantáneas de FlexVols, y no en instantáneas de FlexGroups.




=== 22 de noviembre de 2024

Esta versión de copia de seguridad y recuperación de BlueXP  incluye las siguientes actualizaciones.



==== Modos de protección SnapLock Compliance y SnapLock Enterprise

Ahora, el backup y la recuperación de datos de BlueXP  puede realizar backups de volúmenes en las instalaciones tanto de FlexVol como de FlexGroup configurados mediante modos de protección SnapLock Compliance o SnapLock Enterprise. Los clústeres deben ejecutar ONTAP 9,14 o superior para esta compatibilidad. El backup de los volúmenes de FlexVol con el modo SnapLock Enterprise se admite desde la versión 9.11.1 de ONTAP. Las versiones anteriores de ONTAP no ofrecen compatibilidad para realizar backups de volúmenes de protección de SnapLock.

Consulte la lista completa de los volúmenes compatibles en la https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Descubre el backup y la recuperación de BlueXP"].



==== Indización del proceso de búsqueda y restauración en la página de volúmenes

Para poder utilizar Search & Restore, debe habilitar "Indexing" en cada entorno de trabajo de origen desde el que desea restaurar datos de volumen. Esto permite que el catálogo indexado realice un seguimiento de los archivos de copia de seguridad de cada volumen. Ahora, la página Volúmenes muestra el estado de indexación:

* Indexado: Los volúmenes se han indexado.
* En curso
* No indexado
* Indización en pausa
* Error
* Deshabilitado




== Clasificación



=== 14 de abril de 2025



==== Versión 1,42

Esta versión de clasificación de BlueXP  incluye:

.Análisis masivo para entornos de trabajo
La clasificación BlueXP  ahora admite operaciones masivas para entornos de trabajo. Puede optar por activar la asignación de exploraciones, activar la asignación y clasificación de exploraciones, desactivar exploraciones o crear una configuración personalizada en los volúmenes del entorno de trabajo. Si se realiza una selección para un volumen individual, se anula la selección masiva. Para realizar una operación masiva, navegue a la página **Configuración** y realice su selección.

.Descargue el informe de investigación localmente
La clasificación BlueXP  ahora admite la capacidad de descargar informes de investigación de datos localmente para verlos en el explorador. Si selecciona la opción local, la investigación de datos solo está disponible en formato CSV y solo muestra las primeras 10.000 filas de datos.

Para obtener más información, consulte link:task-investigate-data.html#create-the-data-investigation-report["Investiga los datos almacenados en tu organización con la clasificación BlueXP"].



=== 10 de marzo de 2025



==== Versión 1,41

Esta versión de clasificación de BlueXP  incluye mejoras generales y correcciones de errores. También incluye:

.Estado de adquisición
La clasificación BlueXP  ahora realiza un seguimiento del progreso en tiempo real de las exploraciones de asignación y clasificación _initial_ en un volumen. Las barras progresivas separadas realizan un seguimiento de las exploraciones de mapeo y clasificación, presentando un porcentaje del total de archivos escaneados. También puede pasar el ratón sobre una barra de progreso para ver el número de archivos escaneados y el total de archivos. El seguimiento del estado de sus escaneos crea una visión más profunda del progreso del escaneo, lo que le permite planificar mejor sus escaneos y comprender la asignación de recursos.

Para ver el estado de sus escaneos, vaya a **Configuración** en la clasificación BlueXP  y luego seleccione la **Configuración del entorno de trabajo**. El progreso se muestra en la línea para cada volumen.



=== 19 de febrero de 2025



==== Versión 1,40

Esta versión de clasificación de BlueXP  incluye las siguientes actualizaciones.

.Compatibilidad con RHEL 9,5
Esta versión es compatible con Red Hat Enterprise Linux v9,5 además de las versiones compatibles anteriormente. Esto se aplica a cualquier instalación manual en las instalaciones de la clasificación BlueXP , incluidas las puestas en marcha de sitios oscuros.

Los siguientes sistemas operativos requieren el uso del motor de contenedores Podman y requieren la versión de clasificación BlueXP  1,30 o superior: Red Hat Enterprise Linux versión 8,8, 8,10, 9,0, 9,1, 9,2, 9,3, 9,4 y 9,5.

.Priorice las exploraciones de sólo asignación
Al realizar exploraciones de sólo asignación, puede priorizar las exploraciones más importantes. Esta función ayuda cuando tiene muchos entornos de trabajo y desea garantizar que las exploraciones de alta prioridad se completen primero.

De forma predeterminada, las exploraciones se ponen en cola según el orden en el que se inician. Gracias a la capacidad de dar prioridad a las exploraciones, ahora puede mover las exploraciones al frente de la cola. Se puede priorizar varias adquisiciones. La prioridad se designa en un orden de primero en entrar, primero en salir, lo que significa que la primera exploración que prioriza se mueve al frente de la cola; la segunda exploración que prioriza se convierte en la segunda en la cola, y así sucesivamente.

La prioridad se concede una vez. Las nuevas exploraciones automáticas de los datos de asignación se producen en el orden predeterminado.

La priorización está limitada alink:concept-cloud-compliance.html["exploraciones de sólo asignación"]; no está disponible para las exploraciones de mapas y clasificaciones.

Para obtener más información, consulte link:task-managing-repo-scanning.html#prioritize-scans["Priorice las adquisiciones"].

.Vuelva a intentar todas las adquisiciones
La clasificación BlueXP  ahora admite la capacidad de reintentar por lotes todos los análisis fallidos.

Ahora puede volver a intentar escaneos en una operación por lotes con la función **Reintentar todo**. Si las exploraciones de clasificación fallan debido a un problema temporal, como una interrupción de la red, puede volver a intentar todas las exploraciones al mismo tiempo con un botón en lugar de volver a intentarlo individualmente. Las secuencias se pueden volver a intentar tantas veces como sea necesario.

Para volver a intentar todas las adquisiciones:

. En el menú de clasificación de BlueXP , selecciona *Configuración*.
. Para volver a intentar todos los escaneos fallidos, seleccione *Reintentar todos los escaneos*.


.Precisión mejorada del modelo de categorización
La precisión del modelo de aprendizaje automático link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["categorías predefinidas"]ha mejorado en un 11%.



=== 22 de enero de 2025



==== Versión 1,39

Esta versión de clasificación de BlueXP  actualiza el proceso de exportación del informe de investigación de datos. Esta actualización de exportación es útil para realizar análisis adicionales de sus datos, crear visualizaciones adicionales de los datos o compartir los resultados de su investigación de datos con otros.

Anteriormente, la exportación del informe de investigación de datos se limitaba a 10.000 filas. Con esta versión, el límite se ha eliminado para que pueda exportar todos sus datos. Este cambio le permite exportar más datos de sus informes de investigación de datos, lo que le proporciona más flexibilidad en el análisis de datos.

Puede elegir el entorno de trabajo, los volúmenes, la carpeta de destino y el formato JSON o CSV. El nombre de archivo exportado incluye una marca de tiempo para ayudarle a identificar cuándo se exportaron los datos.

Los entornos de trabajo compatibles incluyen:

* Cloud Volumes ONTAP
* FSX para ONTAP
* ONTAP
* Compartir grupo


La exportación de datos del informe de investigación de datos tiene las siguientes limitaciones:

* El número máximo de registros para descargar es de 500 millones por tipo (archivos, directorios y tablas)
* Se espera que un millón de registros tarde unos 35 minutos en exportarse.


Para obtener más información sobre la investigación de datos y el informe, consulte https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Investiga los datos almacenados en tu organización"].



=== 16 de diciembre de 2024



==== Versión 1,38

Esta versión de clasificación de BlueXP  incluye mejoras generales y correcciones de errores.



== Cloud Volumes ONTAP



=== 14 de abril de 2025



==== Creación de máquinas virtuales de almacenamiento automatizada a través de las API de Google Cloud

Ahora puede usar las API de BlueXP  para automatizar la creación de máquinas virtuales de almacenamiento en Google Cloud. Utiliza esta función en configuraciones de alta disponibilidad (HA) de Cloud Volumes ONTAP y ahora también puede utilizarla en puestas en marcha de un solo nodo. Al utilizar las API de BlueXP , puede crear, cambiar y eliminar fácilmente máquinas virtuales de almacenamiento que sirven datos en su entorno de Google Cloud, sin tener que configurar manualmente las interfaces de red, las LIF y las LIF de gestión requeridas. Esta automatización simplifica el proceso de gestión de máquinas virtuales de almacenamiento.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["Gestione máquinas virtuales de almacenamiento que sirven datos para Cloud Volumes ONTAP en Google Cloud"^]



=== 28 de marzo de 2025



==== Despliegues de modo privado activados para Cloud Volumes ONTAP 9.14.1

Ahora puede poner en marcha Cloud Volumes ONTAP 9.14.1 en modo privado en AWS, Azure y Google Cloud. El modo privado está habilitado para las implementaciones de nodos únicos y de alta disponibilidad (HA) de Cloud Volumes ONTAP 9.14.1.

Para obtener más información sobre los despliegues en modo privado, consulte https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#restricted-mode["Obtenga más información sobre los modos de implementación de BlueXP"^].



=== 12 de marzo de 2025



==== Se admiten nuevas regiones para implementaciones de varias zonas de disponibilidad en Azure

Las siguientes regiones admiten ahora implementaciones de zonas de disponibilidad múltiple de alta disponibilidad en Azure para Cloud Volumes ONTAP 9.12.1 GA y versiones posteriores:

* Estados Unidos Central
* Gobierno de EE. UU. Virginia (Región gubernamental de los EE. UU. - Virginia)


Para obtener una lista de todas las regiones, consulte la https://bluexp.netapp.com/cloud-volumes-global-regions["Mapa de regiones globales en Azure"^].



== Cloud Volumes Service para Google Cloud



=== 9 de septiembre de 2020



==== Compatibilidad con Cloud Volumes Service para Google Cloud

Ahora puede gestionar Cloud Volumes Service para Google Cloud directamente desde BlueXP:

* Configurar y crear un entorno de trabajo
* Cree y gestione volúmenes NFSv3 y NFSv4.1 para clientes de Linux y UNIX
* Crear y gestionar volúmenes de SMB 3.x para clientes Windows
* Crear, eliminar y restaurar copias de Snapshot de volumen




== Copiar y sincronizar



=== 2 de febrero de 2025



==== Nuevo soporte de SO para el agente de datos

El agente de datos ahora es compatible con hosts que ejecutan Red Hat Enterprise 9,4, Ubuntu 23,04 y Ubuntu 24,04.

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["Vea los requisitos del host Linux"].



=== 27 de octubre de 2024



==== Corrección de errores

Actualizamos el servicio de copia y sincronización de BlueXP y el agente de datos para solucionar algunos errores. La nueva versión de Data Broker es 1,0.56.



=== 16 de septiembre de 2024



==== Corrección de errores

Actualizamos el servicio de copia y sincronización de BlueXP y el agente de datos para solucionar algunos errores. La nueva versión de Data Broker es 1,0.55.



== Asesor digital



=== 05 de marzo de 2025



==== Asesor de actualizaciones

* Con Disk Qualification Package (DQP), ahora puede actualizar automáticamente los controladores de disco y el firmware del dispositivo de almacenamiento según los criterios de estado y rendimiento predefinidos. Esto reduce los fallos potenciales y mejora la fiabilidad general del sistema.
* Se ha introducido la base de datos de zona horaria (DB) para mantener automáticamente la alineación del sistema con las últimas definiciones de zona horaria. Esto garantiza que las operaciones dependientes del tiempo continúen sin problemas incluso cuando las reglas de zona horaria cambien.




=== 12 de diciembre de 2024



==== Asesor de actualizaciones

Ahora puede ver el firmware de almacenamiento, el firmware de SP/BMC y el paquete autónomo de ransomware (ARP) que se recomiendan para una actualización. link:https://docs.netapp.com/us-en/active-iq/view-firmware-update-recommendations.html["Aprenda a ver las recomendaciones de actualización de firmware"].



=== 04 de diciembre de 2024



==== Widget AutoSupport

El widget AutoSupport se ha agregado a la pantalla del panel principal para alertar a los clientes sobre los problemas relacionados con el estado de AutoSupport.



== Cartera digital



=== 10 de marzo de 2025



==== Posibilidad de eliminar suscripciones

Ahora puede eliminar suscripciones de la cartera digital si ha cancelado su suscripción.



==== Ver la capacidad consumida para las suscripciones de Marketplace

Al visualizar las suscripciones PAYGO, ahora puede ver la capacidad consumida de la suscripción.



=== 10 de febrero de 2025

La cartera digital de BlueXP  se ha rediseñado para facilitar el uso y ahora proporciona gestión de licencias y suscripciones adicionales.



==== Nuevo panel de información general

La página de inicio de la cartera digital tiene un panel actualizado de tus licencias de NetApp y suscripciones de Marketplace, con la capacidad de profundizar en servicios específicos, tipos de licencias y acciones necesarias.



==== Configurando suscripciones a credenciales

Ahora, la cartera digital de BlueXP  le permite configurar sus suscripciones con las credenciales del proveedor. Normalmente, lo haces cuando te suscribes por primera vez a una suscripción del Marketplace o un contrato anual. El cambio anterior de las credenciales de la suscripción sólo se podía realizar en la página Credenciales.



==== Asociación de suscripciones a organizaciones

Ahora puede actualizar la organización a la que está asociada una suscripción directamente desde la cartera digital.



==== Gestión de licencias de Cloud Volumes ONTAP

Ahora administra las licencias de Cloud Volumes ONTAP a través de la página de inicio o la pestaña *Licencias directas*. Utilice la pestaña *Suscripciones de Marketplace* para ver la información de su suscripción.



=== 5 de marzo de 2024



==== Recuperación ante desastres de BlueXP

La cartera digital de BlueXP ahora te permite gestionar las licencias para la recuperación ante desastres de BlueXP. Es posible añadir licencias, actualizar licencias y ver detalles sobre la capacidad con licencia.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Descubre cómo gestionar las licencias para los servicios de datos de BlueXP"]



=== 30 de julio de 2023



==== Mejoras en los informes de uso

Hay disponibles varias mejoras en los informes de uso de Cloud Volumes ONTAP:

* La unidad TiB ahora se incluye en el nombre de las columnas.
* Ahora se incluye un nuevo campo _node(s)_ para los números de serie.
* Ahora se incluye una nueva columna _Workload Type_ en el informe Storage VMs usage.
* Los nombres de entornos de trabajo ahora se incluyen en los informes de uso de volúmenes y máquinas virtuales de almacenamiento.
* El tipo de volumen _file_ ahora está etiquetado como _Primary (Read/Write)_.
* El tipo de volumen _secondary_ ahora está etiquetado como _Secondary (DP)_.


Para obtener más información sobre los informes de uso, consulte https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Descargar informes de uso"].



== Recuperación tras siniestros



=== 16 de abril de 2025

Versión 4,3



==== Detección programada para máquinas virtuales

La recuperación ante desastres de BlueXP  realiza la detección una vez cada 24 horas. Con esta versión, ahora puede personalizar el programa de detección para satisfacer sus necesidades y reducir el impacto en el rendimiento cuando lo necesite. Por ejemplo, si tiene una gran cantidad de máquinas virtuales, puede configurar la programación de detección para que se ejecute cada 48 horas. Si tiene una cantidad pequeña de máquinas virtuales, puede configurar la programación de detección para que se ejecute cada 12 horas.

Si no wan programa la detección, puede deshabilitar la opción de detección programada y actualizar la detección manualmente en cualquier momento.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Añada sitios de vCenter Server"] .



==== Compatibilidad con almacenes de datos de grupo de recursos

Antes, solo podía crear grupos de recursos por máquinas virtuales. Con esta versión, es posible crear un grupo de recursos por almacenes de datos. Cuando crea un plan de replicación y crea un grupo de recursos para ese plan, se mostrarán todas las máquinas virtuales de un almacén de datos. Esta característica resulta útil si tiene una gran cantidad de máquinas virtuales y desea agruparlas por almacén de datos.

Es posible crear un grupo de recursos con un almacén de datos de las siguientes maneras:

* Cuando se añade un grupo de recursos mediante almacenes de datos, se muestra una lista de almacenes de datos. Puede seleccionar uno o varios almacenes de datos para crear un grupo de recursos.
* Cuando crea un plan de replicación y crea un grupo de recursos dentro del plan, puede ver las máquinas virtuales en los almacenes de datos.


Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"] .



==== Notificaciones de prueba gratuita o vencimiento de licencia

Esta versión proporciona notificaciones de que la prueba gratuita caducará en 60 días para garantizar que tenga tiempo para obtener una licencia. Esta versión también proporciona notificaciones el día en que caduca la licencia.



==== Notificación de actualizaciones de servicio

Con esta versión, aparece un banner en la parte superior para indicar que los servicios se están actualizando y que el servicio se coloca en modo de mantenimiento. El banner aparece cuando el servicio se está actualizando y desaparece cuando se completa la actualización. Aunque puede seguir trabajando en la interfaz de usuario mientras la actualización está en curso, no puede enviar nuevos trabajos. Los trabajos programados se ejecutarán una vez finalizada la actualización y el servicio volverá al modo de producción.



=== 19 de febrero de 2025

Versión 4,2



==== Compatibilidad de ASA R2 para máquinas virtuales y almacenes de datos en almacenamiento VMFS

Esta versión de la recuperación ante desastres de BlueXP  ofrece compatibilidad con ASA R2 para máquinas virtuales y almacenes de datos en almacenamiento VMFS. En un sistema ASA R2, el software ONTAP admite la funcionalidad SAN básica, mientras que quita funciones que no son compatibles con los entornos SAN.

Esta versión admite las siguientes funciones de ASA R2:

* Aprovisionamiento de grupos de consistencia para el almacenamiento primario (únicamente grupo de coherencia plano, es decir, sólo un nivel sin una estructura jerárquica)
* Operaciones de backup (grupo de consistencia) incluida la automatización de SnapMirror


La compatibilidad con ASA R2 en la recuperación ante desastres de BlueXP  utiliza ONTAP 9.16.1.

Si bien los almacenes de datos se pueden montar en un volumen ONTAP o en una unidad de almacenamiento de ASA R2, un grupo de recursos de la recuperación ante desastres de BlueXP  no puede incluir tanto un almacén de datos de ONTAP como uno de ASA R2. Es posible seleccionar un almacén de datos de ONTAP o un almacén de datos de ASA R2 en un grupo de recursos.



=== 30 de octubre de 2024



==== Creación de informes

Ahora puede generar y descargar informes para ayudarle a analizar su paisaje. Los informes prediseñados resumen las recuperaciones tras fallos y las recuperaciones tras fallos, muestran los detalles de la replicación en todos los sitios y muestran los detalles del trabajo de los últimos siete días.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["Crear informes de recuperación tras siniestros"].



==== prueba gratuita de 30 días

Ahora puedes registrarte para disfrutar de una prueba gratuita de 30 días de recuperación ante desastres de BlueXP . Anteriormente, las pruebas gratuitas eran de 90 días.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configurar la licencia"].



==== Desactive y active los planes de replicación

Una versión anterior incluía actualizaciones de la estructura del programa de prueba de conmutación por error, que era necesaria para soportar los programas diarios y semanales. Esta actualización requería deshabilitar y volver a activar todos los planes de replicación existentes para poder utilizar los nuevos programas de prueba de conmutación por error diarios y semanales. Este es un requisito único.

Le contamos cómo:

. En el menú superior, selecciona *Planes de replicación*.
. Seleccione un plan y seleccione el icono Acciones para mostrar el menú desplegable.
. Seleccione *Desactivar*.
. Después de unos minutos, selecciona *Habilitar*.




==== Asignación de carpetas

Al crear un plan de replicación y asignar recursos de computación, ahora puede asignar carpetas de modo que se recuperen las máquinas virtuales en una carpeta que especifique para el centro de datos, el clúster y el host.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"] .



==== Los detalles de la máquina virtual están disponibles para la conmutación al nodo de respaldo, la conmutación de retorno tras recuperación y la conmutación

Cuando se produce un fallo y se inicia una conmutación al respaldo, una conmutación de retorno tras recuperación o una prueba de la conmutación por error, ahora puede ver los detalles de los equipos virtuales e identificar qué equipos virtuales no se reiniciaron.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Conmute al nodo de respaldo de las aplicaciones en un sitio remoto"].



==== Retraso en el arranque de equipos virtuales con una secuencia de arranque ordenada

Al crear un plan de replicación, ahora puede establecer un retraso de inicio para cada VM del plan. De este modo, es posible establecer una secuencia para que las máquinas virtuales se inicien para garantizar que se ejecute toda la prioridad que se tienen unas máquinas virtuales antes de que se inicien las siguientes de prioridad.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"] .



==== Información del sistema operativo del equipo virtual

Al crear un plan de replicación, ahora puede ver el sistema operativo de cada VM del plan. Esto es útil para decidir cómo agrupar máquinas virtuales en un grupo de recursos.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"] .



==== Alias de nombres de VM

Al crear un plan de replicación, ahora puede agregar un prefijo y un sufijo a los nombres de los equipos virtuales en el área de recuperación ante desastres. Esto permite usar un nombre más descriptivo para las máquinas virtuales del plan.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"] .



==== Limpie las instantáneas antiguas

Es posible eliminar las copias de Snapshot que ya no se necesiten más allá del recuento de retención especificado. Las copias Snapshot pueden acumularse con el tiempo al reducir el número de retención de snapshots y ahora puede quitarlas para liberar espacio. Puede hacerlo en cualquier momento bajo demanda o cuando elimine un plan de replicación.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Administre la información de sitios, grupos de recursos, planes de replicación, almacenes de datos y máquinas virtuales"] .



==== Conciliar instantáneas

Ahora puede conciliar instantáneas que no estén sincronizadas entre el origen y el destino. Esto puede suceder si se eliminan las copias Snapshot en un destino fuera de la recuperación tras desastres de BlueXP . El servicio elimina la snapshot de origen automáticamente cada 24 horas. Sin embargo, puede realizar esto bajo demanda. Esta función le permite asegurarse de que las instantáneas sean coherentes en todos los sitios.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestionar planes de replicación"] .



== Sistemas E-Series



=== 18 de septiembre de 2022



==== Compatibilidad con E-Series

Ahora puedes detectar tus sistemas E-Series directamente en BlueXP. El descubrimiento de sistemas E-Series le ofrece una visión completa de los datos en su multicloud híbrido.



== Eficiencia económica



=== 15 de mayo de 2024



==== Operaciones desactivadas

Algunas de las funciones de eficiencia económica de BlueXP  se han desactivado temporalmente:

* Renovación tecnológica
* Añadir capacidad




=== 14 de marzo de 2024



==== Opciones de actualización tecnológica

Si tienes activos implementados y quieres determinar si es necesario actualizar una tecnología, puedes utilizar las opciones de actualización de la tecnología de eficiencia económica de BlueXP. Puede revisar una breve evaluación de sus cargas de trabajo actuales y recibir recomendaciones, o bien si envió registros de AutoSupport a NetApp en los últimos 90 días, el servicio ahora puede proporcionar una simulación de cargas de trabajo para ver el rendimiento de las cargas de trabajo en hardware nuevo.

También puede agregar una carga de trabajo y excluir las cargas de trabajo existentes de la simulación.

Anteriormente, solo podía realizar una evaluación de sus activos e identificar si se recomienda una actualización tecnológica.

Ahora la función forma parte de la opción Tech Refresh de la barra de navegación izquierda.

Obtenga más información sobre el https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["Evaluar una actualización tecnológica"].



=== 08 de noviembre de 2023



==== Renovación tecnológica

Esta versión de la eficiencia económica de BlueXP incluye una nueva opción para realizar una evaluación de sus activos e identificar si se recomienda una actualización tecnológica. El servicio incluye una nueva opción de actualización tecnológica en la navegación izquierda, nuevas páginas en las que puede realizar una evaluación de sus activos y cargas de trabajo actuales, y un informe que le ofrece recomendaciones.



== Almacenamiento en caché en el edge

El servicio de almacenamiento en caché perimetral de BlueXP  se eliminó el 7 de agosto de 2024.



== Google Cloud Storage



=== 10 de julio de 2023



==== Capacidad para añadir nuevos bloques y gestionar bloques existentes desde BlueXP

Has tenido la capacidad de ver buckets de almacenamiento de Google Cloud en BlueXP Canvas durante bastante tiempo. Ahora puede agregar nuevos cubos y cambiar las propiedades de los cubos existentes directamente desde BlueXP . https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["Descubre cómo añadir nuevos buckets de Google Cloud Storage"].



== Kubernetes

El 7 de agosto de 2024 se eliminó la compatibilidad para detectar y gestionar clústeres de Kubernetes.



== Informes de migración

El servicio de informes de migración de BlueXP  se eliminó el 7 de agosto de 2024.



== Clústeres de ONTAP en las instalaciones



=== 26 de noviembre de 2024



==== Compatibilidad con sistemas ASA R2 con modo privado

Ahora puede descubrir los sistemas NetApp ASA R2 al utilizar BlueXP  en modo privado. Esta asistencia está disponible a partir de la versión 3.9.46 del modo privado de BlueXP .

* https://docs.netapp.com/us-en/asa-r2/index.html["Obtenga más información sobre los sistemas R2 de ASA"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"^]




=== 7 de octubre de 2024



==== Compatibilidad con los sistemas ASA R2

Ahora puede detectar los sistemas NetApp ASA R2 en BlueXP  cuando se utiliza BlueXP  en modo estándar o restringido. Después de detectar un sistema NetApp ASA R2 y abrir el entorno de trabajo, se le pasará directamente a System Manager.

No hay otras opciones de gestión disponibles con los sistemas ASA R2. No se puede utilizar la vista estándar y no se pueden habilitar los servicios de BlueXP.

La detección de sistemas ASA R2 no es compatible cuando se usa BlueXP  en el modo privado.

* https://docs.netapp.com/us-en/asa-r2/index.html["Obtenga más información sobre los sistemas R2 de ASA"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"^]




=== 22 de abril de 2024



==== Ya no se admiten plantillas de volumen

Ya no puede crear un volumen a partir de una plantilla. Esta acción se asoció con el servicio de corrección de BlueXP, que ya no está disponible.



== Resiliencia operativa



=== 02 de abril de 2023



==== Servicio de resiliencia operativa de BlueXP

Mediante el nuevo servicio de resiliencia operativa de BlueXP y sus sugerencias automatizadas para la corrección de los riesgos operativos TECNOLÓGICOS, puedes implementar soluciones sugeridas antes de que se produzca una interrupción o un fallo.

La resiliencia operativa es un servicio que le ayuda a analizar las alertas y los eventos para mantener el estado, el tiempo de actividad y el rendimiento de los servicios y las soluciones.

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["Obtenga más información sobre la resiliencia operativa de BlueXP"].



== Protección contra ransomware



=== 14 de abril de 2025



==== Informes de detalle de preparación

Con este lanzamiento, puede revisar los informes simulacros de preparación para los ataques de ransomware. Un ejercicio de preparación le permite simular un ataque de ransomware en una carga de trabajo de muestra recién creada. A continuación, investigue el ataque simulado y recupere la carga de trabajo de muestra. Esta función te ayuda a saber que estás preparado en caso de un ataque real de ransomware mediante la prueba de los procesos de notificación de alertas, respuesta y recuperación.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Haz un simulacro de preparación para los ataques de ransomware"] .



==== Nuevos roles y permisos de control de acceso basado en roles

Antes, podrías asignar roles y permisos a los usuarios en función de sus responsabilidades, lo que te ayudaba a gestionar el acceso de los usuarios a la protección frente al ransomware de BlueXP . Con esta versión, hay dos roles nuevos específicos de la protección contra ransomware de BlueXP  con permisos actualizados. Los nuevos roles son los siguientes:

* Administrador de protección frente a ransomware
* Visor de protección contra ransomware


Para obtener más información sobre los permisos, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["Acceso a funciones basado en roles de protección frente al ransomware de BlueXP"] .



==== Mejoras de pago

Esta versión incluye varias mejoras en el proceso de pago.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["Configurar opciones de licencia y pago"] .



=== 10 de marzo de 2025



==== Simule un ataque y responda

Con este lanzamiento, simule un ataque de ransomware para probar su respuesta a una alerta de ransomware. Esta función te ayuda a saber que estás preparado en caso de un ataque real de ransomware mediante la prueba de los procesos de notificación de alertas, respuesta y recuperación.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Haz un simulacro de preparación para los ataques de ransomware"] .



==== Mejoras en el proceso de detección

Esta versión incluye mejoras en los procesos selectivos de detección y redetección:

* Con esta versión, puede detectar las cargas de trabajo recién creadas que se agregaron a los entornos de trabajo seleccionados anteriormente.
* También puede seleccionar entornos de trabajo _NEW_ en esta versión. Esta función le ayuda a proteger las nuevas cargas de trabajo añadidas a su entorno.
* Es posible realizar estos procesos de detección durante el proceso de detección inicial o dentro de la opción Configuración.


Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Detectar las cargas de trabajo recién creadas para los entornos de trabajo seleccionados anteriormente"] y. https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["Configure las funciones con la opción Configuración"]



==== Se generan alertas cuando se detecta un cifrado alto

Con esta versión, puede ver alertas cuando se detecta un alto cifrado en sus cargas de trabajo incluso sin cambios de extensiones de archivos grandes. Esta función, que utiliza la IA de protección autónoma frente a ransomware (ARP) de ONTAP, le ayuda a identificar cargas de trabajo que están en riesgo de ataques de ransomware. Utilice esta función y descargue la lista completa de archivos afectados con o sin cambios de extensión.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Responder a una alerta de ransomware detectada"] .



=== 16 de diciembre de 2024



==== Detectar comportamientos anómalos de usuarios con la seguridad de carga de trabajo de almacenamiento de Data Infrastructure Insights

Con esta versión, puedes utilizar Data Infrastructure Insights Storage Workload Security para detectar comportamientos anómalos de los usuarios en tus cargas de trabajo de almacenamiento. Esta función te ayuda a identificar posibles amenazas de seguridad y a bloquear usuarios potencialmente maliciosos para proteger tus datos.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Responder a una alerta de ransomware detectada"] .

Antes de usar la seguridad de la carga de trabajo de almacenamiento de información de la infraestructura de datos para detectar un comportamiento anómalo del usuario, debe configurar la opción mediante la opción *Configuración* de protección contra ransomware de BlueXP .

Consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["Configura las opciones de protección contra ransomware de BlueXP"].



==== Seleccione las cargas de trabajo que desea detectar y proteger

Con esta versión, ahora puede hacer lo siguiente:

* Dentro de cada conector, seleccione los entornos de trabajo donde desea detectar las cargas de trabajo. Esta función puede beneficiarse si desea proteger cargas de trabajo específicas en su entorno y no para otras.
* Durante la detección de cargas de trabajo, puede habilitar la detección automática de cargas de trabajo por conector. Esta función permite seleccionar las cargas de trabajo que se desean proteger.
* Detectar las cargas de trabajo recién creadas para los entornos de trabajo seleccionados anteriormente.


Consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Detectar cargas de trabajo"].



== Reparación

El servicio de corrección de BlueXP se eliminó el 22 de abril de 2024.



== Replicación



=== 18 de septiembre de 2022



==== FSX para ONTAP a Cloud Volumes ONTAP

Ahora puede replicar datos de un sistema de archivos Amazon FSX para ONTAP en Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Aprenda a configurar la replicación de datos"].



=== 31 de julio de 2022



==== FSX para ONTAP como origen de datos

Ahora puede replicar datos de un sistema de archivos Amazon FSX para ONTAP en los siguientes destinos:

* Amazon FSX para ONTAP
* Clúster de ONTAP en las instalaciones


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Aprenda a configurar la replicación de datos"].



=== 2 de septiembre de 2021



==== Compatibilidad con Amazon FSX para ONTAP

Ahora puede replicar datos desde un sistema Cloud Volumes ONTAP o un clúster de ONTAP en las instalaciones en un sistema de archivos Amazon FSX para ONTAP.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Aprenda a configurar la replicación de datos"].



== Actualizaciones de software



=== 02 de abril de 2025



==== Reducción de riesgos

En la sección de resumen de las actualizaciones de software de BlueXP , ahora puede ver el número total de riesgos que se pueden mitigar mediante la actualización del sistema operativo. Esto permite a los usuarios evaluar las mejoras de seguridad y estabilidad en su base de instalación.



=== 07 de agosto de 2024



==== Actualización de ONTAP

El servicio de actualizaciones de software de BlueXP  ofrece a los usuarios una experiencia de actualización fluida al mitigar los riesgos y garantizar que los clientes puedan sacar el máximo partido a las funciones de ONTAP.

Más información sobre link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["Actualizaciones de software de BlueXP"].



== StorageGRID



=== 7 de agosto de 2024



==== Nueva vista avanzada

A partir de StorageGRID 11,8, puede utilizar la conocida interfaz de Grid Manager para gestionar su sistema StorageGRID desde BlueXP .

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["Aprenda a administrar StorageGRID con la vista avanzada"].



==== Capacidad para revisar y aprobar el certificado de interfaz de gestión de StorageGRID

Ahora puede revisar y aprobar un certificado de interfaz de gestión de StorageGRID al detectar el sistema StorageGRID de BlueXP . También se puede revisar y aprobar el último certificado de interfaz de gestión de StorageGRID en una cuadrícula detectada.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Aprenda a revisar y aprobar el certificado de servidor durante la detección del sistema."]



=== 18 de septiembre de 2022



==== Compatibilidad con StorageGRID

Ahora puede descubrir sus sistemas StorageGRID directamente desde BlueXP. El descubrimiento de StorageGRID le ofrece una visión completa de los datos en su multicloud híbrido.



== Organización en niveles



=== 9 de agosto de 2023



==== Utilice un prefijo personalizado para el nombre del depósito

Anteriormente, era necesario utilizar el prefijo predeterminado «fabric-pool» al definir el nombre del bucket, por ejemplo, _fabric-pool-bucket1_. Ahora puede utilizar un prefijo personalizado al asignar un nombre a su cubo. Esta funcionalidad solo está disponible cuando se organizan los datos en niveles en Amazon S3. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["Leer más"].



==== Busca un clúster en todos los conectores de BlueXP

Si utiliza varios conectores para gestionar todos los sistemas de almacenamiento del entorno, algunos clústeres en los que desea implementar la organización en niveles pueden estar en conectores diferentes. Si no estás seguro de qué Connector gestiona un determinado clúster, puedes buscar en todos los conectores mediante la organización en niveles de BlueXP. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["Leer más"].



=== 4 de julio de 2023



==== Ajuste el ancho de banda para transferir datos inactivos

Al activar la organización en niveles de BlueXP, ONTAP puede utilizar una cantidad ilimitada de ancho de banda de red para transferir los datos inactivos de los volúmenes del clúster al almacenamiento de objetos. Si observa que el tráfico por niveles afecta a las cargas de trabajo normales de usuario, puede limitar la cantidad de ancho de banda que se puede utilizar durante la transferencia. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["Leer más"].



==== Evento de organización en niveles que se muestra en el Centro de notificaciones

El evento de organización en niveles «Almacenar los datos adicionales del clúster <name> en el almacenamiento de objetos para aumentar la eficiencia del almacenamiento» aparece ahora como una notificación cuando un clúster está organizando en niveles menos del 20 % de sus datos inactivos, incluidos los clústeres que organizan en niveles ningún dato.

Esta notificación es una «recomendación» que pretende hacer que sus sistemas sean más eficientes y ahorrar costes de almacenamiento. Proporciona un enlace al https://bluexp.netapp.com/cloud-tiering-service-tco["Calculadora de ahorro y coste total de propiedad de la organización en niveles de BlueXP"^] para ayudarle a calcular el ahorro de costes.



=== 3 de abril de 2023



==== Se ha eliminado la pestaña de licencias

La pestaña Licencias se ha eliminado de la interfaz de organización en niveles de BlueXP. Ahora, se accede a todas las licencias de suscripciones de pago por uso (PAYGO) desde la consola de organización en niveles de BlueXP en las instalaciones. También hay un enlace desde esa página a la cartera digital de BlueXP para que puedas ver y gestionar cualquier producto con tus propias licencias (BYOL) en la organización en niveles de BlueXP.



==== Se ha cambiado el nombre de las pestañas de organización en niveles y se han actualizado

Se ha cambiado el nombre de la pestaña «Consola de clústeres» a «Clusters» y la pestaña «On-Prem Overview» se ha cambiado a «On-premises Dashboard». Estas páginas han añadido información que le ayudará a evaluar si puede optimizar el espacio de almacenamiento con una configuración adicional de organización en niveles.



== Almacenamiento en caché de volúmenes



=== 04 de junio de 2023



==== Almacenamiento en caché de volúmenes

El almacenamiento en caché de volúmenes, una función del software ONTAP 9, es una funcionalidad de almacenamiento en caché remoto que simplifica la distribución de archivos, reduce la latencia WAN al acercar los recursos a dónde están los usuarios y los recursos informáticos y reduce los costes de ancho de banda WAN. El almacenamiento en caché de volúmenes proporciona un volumen persistente y editable en un lugar remoto. Puede usar el almacenamiento en caché de volúmenes de BlueXP para acelerar el acceso a los datos o para descargar el tráfico de volúmenes con un acceso frecuente. Los volúmenes de caché son ideales para las cargas de trabajo de lectura intensiva, especialmente cuando los clientes necesitan acceder a los mismos datos de manera repetida.

Con el almacenamiento en caché de volúmenes de BlueXP, dispones de capacidades de almacenamiento en caché para la nube, específicamente para Amazon FSx para NetApp ONTAP, Cloud Volumes ONTAP y on-premises como entornos de trabajo.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["Obtén más información sobre el almacenamiento en caché de volúmenes de BlueXP"].



== Fábrica de cargas de trabajo



=== 30 de marzo de 2025



==== CloudShell informa de respuestas de errores generadas por IA para comandos de la CLI de ONTAP

Al usar CloudShell, cada vez que emita un comando de la CLI de ONTAP y se produce un error, puede obtener respuestas de error generadas por IA que incluyen una descripción del fallo, la causa del fallo y una resolución detallada.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Usar CloudShell"]



==== iam:SimulatePermissionPolicy actualización de permisos

Ahora puede administrar `iam:SimulatePrincipalPolicy` el permiso desde la consola de fábrica de cargas de trabajo cuando agrega credenciales de cuenta de AWS adicionales o agrega una nueva capacidad de carga de trabajo, como la carga de trabajo de GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Log de cambios de referencia de permisos"]



=== 02 de febrero de 2025



==== CloudShell disponible en la consola de fábrica de cargas de trabajo de BlueXP

CloudShell está disponible desde cualquier lugar de la consola de fábrica de cargas de trabajo de BlueXP . CloudShell le permite usar las credenciales de AWS y ONTAP que ha proporcionado en su cuenta de BlueXP  y ejecutar comandos de la CLI de AWS o comandos de la CLI de ONTAP en un entorno similar al shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Usar CloudShell"]



==== Actualización de permisos para bases de datos

El siguiente permiso ahora está disponible en el modo _READ_ para bases de datos `iam:SimulatePrincipalPolicy`: .

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Log de cambios de referencia de permisos"]



=== 22 de enero de 2025



==== Permisos de fábrica de cargas de trabajo de BlueXP

Ahora puede ver los permisos que utiliza la fábrica de carga de trabajo de BlueXP  para ejecutar diversas operaciones, comenzando desde la detección de sus entornos de almacenamiento hasta la implementación de recursos de AWS, como sistemas de archivos en almacenamiento o bases de conocimientos para cargas de trabajo de GenAI. Es posible ver políticas y permisos de IAM para almacenamiento, bases de datos, VMware y cargas de trabajo de GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Permisos de fábrica de cargas de trabajo de BlueXP"]
