---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery' 
summary: Conozca los cambios más recientes en los servicios en la nube que forman parte de la plataforma BlueXP. 
---
= Cambios recientes en BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Conozca los cambios más recientes en los servicios en la nube que forman parte de la plataforma BlueXP. Para obtener un historial de versiones completo, vaya a link:release-notes-index.html["conjunto completo de notas de la versión"] por cada servicio individual.



== Funciones administrativas

En esta sección se describen las nuevas funciones relacionadas con las funciones de administración de BlueXP: Cuentas, conectores, credenciales de proveedores de nube y mucho más.



=== 14 de julio de 2025



==== Conector 3.9.54

Esta versión del conector BlueXP incluye mejoras de seguridad, correcciones de errores y las siguientes características nuevas:

* Compatibilidad con servidores proxy transparentes para conectores dedicados a respaldar los servicios de Cloud Volumes ONTAP . link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Obtenga más información sobre cómo configurar un proxy transparente."]
* Capacidad de usar etiquetas de red para ayudar a enrutar el tráfico del conector cuando este se implementa en un entorno de Google Cloud.
* Notificaciones adicionales dentro del producto para la monitorización del estado del conector, incluido el uso de CPU y RAM.


En este momento, la versión 3.9.54 está disponible para el modo estándar y el modo restringido.



==== Gestión de acceso e identidades (IAM) de BlueXP

La gestión de identidad y acceso en BlueXP ahora ofrece las siguientes funciones:

* Soporte para IAM en modo privado, lo que le permite administrar el acceso de los usuarios y los permisos para los servicios y aplicaciones de BlueXP .
* Gestión optimizada de federaciones de identidad, que incluye una navegación más sencilla, opciones más claras para configurar conexiones federadas y una mejor visibilidad de las federaciones existentes.
* Roles de acceso para BlueXP backup and recovery, BlueXP disaster recovery y administración de la federación.




===== Compatibilidad con IAM en modo privado

BlueXP ahora admite IAM en modo privado, lo que permite administrar el acceso y los permisos de los usuarios para los servicios y aplicaciones de BlueXP . Esta mejora permite a los clientes del modo privado aprovechar el control de acceso basado en roles (RBAC) para mejorar la seguridad y el cumplimiento normativo.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#iam["Obtenga más información sobre IAM en BlueXP."]



===== Gestión optimizada de federaciones de identidad

BlueXP ahora ofrece una interfaz más intuitiva para gestionar la federación de identidades. Esto incluye una navegación más sencilla, opciones más claras para configurar conexiones federadas y una mejor visibilidad de las federaciones existentes.

Al habilitar el inicio de sesión único (SSO) mediante la federación de identidades, los usuarios pueden iniciar sesión en BlueXP con sus credenciales corporativas. Esto mejora la seguridad, reduce el uso de contraseñas y simplifica la incorporación.

Se le solicitará que importe las conexiones federadas existentes a la nueva interfaz para acceder a las nuevas funciones de administración. Esto le permite aprovechar las últimas mejoras sin tener que recrear sus conexiones federadas. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-federation-import.html["Obtenga más información sobre cómo importar su conexión federada existente a BlueXP."]

Una gestión mejorada de la federación le permite:

* Agregue más de un dominio verificado a una conexión federada, lo que le permitirá utilizar múltiples dominios con el mismo proveedor de identidad (IdP).
* Deshabilite o elimine las conexiones federadas cuando sea necesario, lo que le otorgará control sobre el acceso y la seguridad de los usuarios.
* Controle el acceso a la gestión de la federación con roles de IAM.


link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-federation.html["Obtenga más información sobre la federación de identidad en BlueXP."]



===== Nuevos roles de acceso para la BlueXP backup and recovery, la BlueXP disaster recovery y la administración de la federación

BlueXP ahora admite el uso de roles de IAM para las siguientes funciones y servicios de datos:

* Backup y recuperación de BlueXP
* Recuperación ante desastres de BlueXP
* Federación


link:https://docs.netapp.com/us-en/bluexp-admin/reference-iam-predefined-roles.html["Obtenga más información sobre el uso de roles de acceso."]



=== 9 de junio de 2025



==== Conector 3.9.53

Esta versión del conector BlueXP incluye mejoras de seguridad y correcciones de errores.

La versión 3.9.53 está disponible para el modo estándar y el modo restringido.



==== Alertas de uso de espacio en disco

El Centro de notificaciones ahora incluye alertas sobre el uso del espacio en disco en el Conector. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#monitor-disk-space["Leer más."^]



==== Mejoras en la auditoría

La Cronología ahora incluye eventos de inicio y cierre de sesión de los usuarios. Puedes ver la actividad de inicio de sesión, lo que facilita la auditoría y la supervisión de la seguridad. Los usuarios de la API con el rol de administrador de la organización pueden ver la dirección de correo electrónico del usuario que inició sesión incluyendo el...  `includeUserData=true`` parámetro como en el siguiente:  `/audit/<account_id>?includeUserData=true` .



==== Gestión de suscripciones de Keystone disponible en BlueXP

Puede administrar su suscripción a NetApp Keystone desde BlueXP.

link:https://docs.netapp.com/us-en/keystone-staas/index.html["Obtenga información sobre la gestión de suscripciones de Keystone en BlueXP."^]



==== Gestión de acceso e identidades (IAM) de BlueXP



===== Autenticación multifactor (MFA)

Los usuarios no federados pueden habilitar la MFA en sus cuentas de BlueXP para mejorar la seguridad. Los administradores pueden gestionar la configuración de la MFA, incluyendo restablecerla o deshabilitarla para los usuarios según sea necesario. Esto solo es compatible en el modo estándar.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-user-settings.html#task-user-mfa["Obtenga información sobre cómo configurar la autenticación multifactor para usted."^] link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#manage-mfa["Obtenga información sobre cómo administrar la autenticación multifactor para los usuarios."^]



==== Cargas de trabajo

Ahora puede ver y eliminar las credenciales de Amazon FSx para NetApp ONTAP desde la página Credenciales en BlueXP.



=== 29 de mayo de 2025



==== Versión en modo privado (3,9.52)

Ya está disponible una nueva versión de modo privado para descargar desde el https://mysupport.netapp.com/site/downloads["Sitio de soporte de NetApp"^]

La versión 3.9.52 incluye actualizaciones para los siguientes componentes y servicios de BlueXP.

[cols="3*"]
|===
| Componente o servicio | Versión incluida en esta versión | Cambios desde la versión anterior del modo privado 


| Conector | 3.9.52, 3.9.51 | Ir a la  https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["Novedades en la página de conectores de BlueXP"] y consulte los cambios incluidos para las versiones 3.9.52 y 3.9.50. 


| Backup y recuperación | 12 de mayo de 2025 | Ir a la  https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["Novedades en la página de backup y recuperación de BlueXP"^] y consulte los cambios incluidos en la versión de mayo de 2025. 


| Clasificación | 12 de mayo de 2025 (versión 1.43) | Vaya a https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["Novedades en la página de clasificación de BlueXP"^] y consulte los cambios incluidos en las versiones de 1,38 a 1.371.41. 
|===
Para obtener más información sobre el modo privado, incluido el modo de actualización, consulte lo siguiente:

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Aprende sobre el modo privado"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Descubre cómo empezar a utilizar BlueXP en modo privado"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["Aprenda a actualizar el conector cuando use el modo privado"]




== Alertas



=== 7 de octubre de 2024



==== La página de lista de alertas de BlueXP

Usted puede identificar rápidamente clústeres de ONTAP con poca capacidad o bajo rendimiento, medir el grado de la disponibilidad e identificar los riesgos de seguridad. Es posible ver alertas relacionadas con la capacidad, el rendimiento, la protección, la disponibilidad, la seguridad y la configuración.



==== Detalles de alertas

Puede profundizar en los detalles de alertas y buscar recomendaciones.



==== Ver los detalles del clúster vinculados a ONTAP System Manager

Con las alertas de BlueXP , puede ver las alertas asociadas con su entorno de almacenamiento de ONTAP y obtener detalles vinculados a System Manager de ONTAP.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["Más información sobre las alertas de BlueXP"].



== Amazon FSX para ONTAP



=== 29 de junio de 2025



==== Actualización de credenciales

Después de configurar las credenciales y los permisos para su sistema de archivos de FSx for ONTAP, se le redirigirá a la página Credenciales de BlueXP. Desde esta página, puede cambiar el nombre o eliminar sus credenciales de FSx for ONTAP.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html["Configurar permisos para FSx para sistemas de archivos ONTAP"]



==== Soporte para replicar datos entre dos sistemas de archivos FSx para ONTAP

La replicación de datos ahora está disponible entre dos sistemas de archivos FSx para ONTAP desde la consola BlueXP.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-working-environment.html#replicate-data["Replicar datos"]



=== 04 de mayo de 2025



==== Soporte de respuesta del rastreador

Tracker ahora proporciona respuestas API para que pueda ver la salida de la API de REST en relación con la tarea.



==== Soporte de autenticación de enlaces para AWS Secrets Manager

Ahora tiene la opción de utilizar secretos de AWS Secrets Manager para autenticar enlaces de modo que no tenga que utilizar las credenciales almacenadas en cargas de trabajo de BlueXP .

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Conéctese a un sistema de archivos FSx para ONTAP con un enlace Lambda"]



==== Implemente las prácticas recomendadas para un sistema de archivos FSx para ONTAP

Cargas de trabajo de BlueXP  proporciona un panel en el que se puede revisar el estado bien estructurado de las configuraciones del sistema de archivos. Puede aprovechar este análisis para implementar prácticas recomendadas para sus sistemas de archivos FSx para ONTAP. El análisis de configuración del sistema de archivos incluye las siguientes configuraciones: Umbral de capacidad de SSD, snapshots locales programados, backups programados de FSx para ONTAP, organización en niveles de datos y replicación de datos remota.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Obtenga más información sobre el análisis bien diseñado para las configuraciones de sistemas de archivos"]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html["Implemente prácticas recomendadas para sus sistemas de archivos"]




==== Notificación bien diseñada para problemas del sistema de archivos

En la consola de BlueXP , los sistemas de archivos FSX para ONTAP con problemas bien diseñados ahora muestran una notificación en el lienzo que indica cuándo los sistemas de archivos tienen problemas que corregir.



==== Terminología de permisos actualizada

La interfaz de usuario y la documentación de la fábrica de carga de trabajo ahora usan "solo lectura" para referirse a los permisos de lectura y "lectura/escritura" para referirse a los permisos de automatización.



=== 30 de marzo de 2025



==== iam:SimulatePermissionPolicy actualización de permisos

Ahora puede administrar `iam:SimulatePrincipalPolicy` el permiso desde la consola de BlueXP  cuando agrega credenciales de cuenta de AWS adicionales o agrega una nueva capacidad de carga de trabajo, como la carga de trabajo de GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Log de cambios de referencia de permisos"^]



== Almacenamiento Amazon S3



=== 5 de marzo de 2023



==== Posibilidad de añadir nuevos cubos desde BlueXP

Has tenido la posibilidad de ver cubos de Amazon S3 en BlueXP Canvas durante mucho tiempo. Ahora puede agregar nuevos cubos y cambiar las propiedades de los cubos existentes directamente desde BlueXP . https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["Descubra cómo añadir nuevos bloques de Amazon S3"].



== Almacenamiento de Azure Blob



=== 5 de junio de 2023



==== Capacidad de añadir nuevas cuentas de almacenamiento desde BlueXP

Has tenido la capacidad de ver Azure Blob Storage en BlueXP Canvas durante bastante tiempo. Ahora puede añadir nuevas cuentas de almacenamiento y cambiar las propiedades de las cuentas de almacenamiento existentes directamente desde BlueXP . https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["Descubre cómo añadir nuevas cuentas de almacenamiento de Azure Blob"].



== Azure NetApp Files



=== 13 de enero de 2025



==== Las funciones de red ahora son compatibles con BlueXP

Al configurar un volumen en Azure NetApp Files desde BlueXP , ahora se pueden indicar las funciones de red. Se alinea con la funcionalidad disponible en la Azure NetApp Files nativa.



=== 12 de junio de 2024



==== Se requiere un nuevo permiso

Ahora se necesita el siguiente permiso para gestionar Azure NetApp Files Volumes desde BlueXP:

Microsoft.Network/virtualNetworks/subnets/read

Se necesita este permiso para leer una subred de red virtual.

Si actualmente está gestionando Azure NetApp Files desde BlueXP, debe añadir este permiso al rol personalizado asociado a la aplicación Microsoft Entra que creó anteriormente.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["Aprenda a configurar una aplicación de Microsoft Entra y ver los permisos de rol personalizados"].



=== 22 de abril de 2024



==== Ya no se admiten plantillas de volumen

Ya no puede crear un volumen a partir de una plantilla. Esta acción se asoció con el servicio de corrección de BlueXP, que ya no está disponible.



== Backup y recuperación



=== 14 de julio de 2025

Esta versión de copia de seguridad y recuperación de BlueXP  incluye las siguientes actualizaciones.



==== Panel de control de volumen de ONTAP mejorado

En abril de 2025, lanzamos una vista previa de un panel de volumen de ONTAP mejorado que es mucho más rápido y eficiente.

Este panel se diseñó para ayudar a los clientes empresariales con un gran número de cargas de trabajo. Incluso para clientes con 20 000 volúmenes, el nuevo panel se carga en menos de 10 segundos.

Tras una vista previa exitosa y los excelentes comentarios de nuestros clientes, ahora la convertimos en la experiencia predeterminada para todos nuestros clientes. Prepárense para un panel de control increíblemente rápido.

Para obtener más información, consulte link:br-use-dashboard.html["Ver el estado de la protección en el Panel de Control"].



==== Compatibilidad con cargas de trabajo de Microsoft SQL Server como versión preliminar de tecnología pública

Esta versión de BlueXP backup and recovery ofrece una interfaz de usuario actualizada que permite administrar las cargas de trabajo de Microsoft SQL Server mediante una estrategia de protección 3-2-1, similar a la del servicio de BlueXP backup and recovery . Con esta nueva versión, puede realizar copias de seguridad de estas cargas de trabajo en el almacenamiento principal, replicarlas en el almacenamiento secundario y, finalmente, en el almacenamiento de objetos en la nube.

Puedes registrarte para la vista previa completando esto  https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["Vista previa del formulario de registro"^] .


NOTE: ESTA DOCUMENTACIÓN SOBRE LA PROTECCIÓN DE LAS CARGAS DE TRABAJO DE MICROSOFT SQL SERVER SE PROPORCIONA COMO UNA VISTA PREVIA DE LA TECNOLOGÍA. Con esta oferta de vista previa, NetApp se reserva el derecho de modificar los detalles, el contenido y la línea de tiempo de la oferta antes de la disponibilidad general.

Esta versión de BlueXP backup and recovery incluye las siguientes actualizaciones:

* *Capacidad de respaldo 3-2-1*: esta versión integra las capacidades de SnapCenter , lo que le permite administrar y proteger sus recursos de SnapCenter con una estrategia de protección de datos 3-2-1 desde la interfaz de usuario de BlueXP backup and recovery .
* *Importar desde SnapCenter*: puede importar datos y políticas de respaldo de SnapCenter al BlueXP backup and recovery.
* *Una interfaz de usuario rediseñada* proporciona una experiencia más intuitiva para administrar sus tareas de copia de seguridad y recuperación.
* *Objetivos de respaldo*: puede agregar depósitos en entornos de Amazon Web Services (AWS), Microsoft Azure Blob Storage, StorageGRID y ONTAP S3 para usarlos como destinos de respaldo para sus cargas de trabajo de Microsoft SQL Server.
* *Compatibilidad con cargas de trabajo*: Esta versión permite realizar copias de seguridad, restaurar, verificar y clonar bases de datos y grupos de disponibilidad de Microsoft SQL Server. (Se añadirá compatibilidad con otras cargas de trabajo en futuras versiones).
* *Opciones de restauración flexibles*: Esta versión le permite restaurar bases de datos en ubicaciones originales y alternativas en caso de corrupción o pérdida accidental de datos.
* *Copias de producción instantáneas*: genere copias de producción que ahorren espacio para desarrollo, pruebas o análisis en minutos en lugar de horas o días.
* Esta versión incluye la capacidad de crear informes detallados.


Para obtener detalles sobre cómo proteger las cargas de trabajo de Microsoft SQL Server, consulte link:br-use-mssql-protect-overview.html["Descripción general de la protección de las cargas de trabajo de Microsoft SQL Server"] .



=== 9 de junio de 2025

Esta versión de copia de seguridad y recuperación de BlueXP  incluye las siguientes actualizaciones.



==== Actualizaciones de soporte del catálogo indexado

En febrero de 2025, presentamos la función de indexación actualizada (Catálogo Indexado v2) que se utiliza durante el método de búsqueda y restauración de datos. La versión anterior mejoró significativamente el rendimiento de la indexación de datos en entornos locales. Con esta versión, el catálogo de indexación ya está disponible en entornos de Amazon Web Services, Microsoft Azure y Google Cloud Platform (GCP).

Si es un cliente nuevo, el Catálogo Indexado v2 está habilitado de forma predeterminada para todos los entornos nuevos. Si ya es cliente, puede reindexar su entorno para aprovechar el Catálogo Indexado v2.

.¿Cómo se habilita la indexación?
Para poder utilizar el método de búsqueda y restauración de datos, debe activar la indexación en cada entorno de trabajo de origen desde el que tiene pensado restaurar volúmenes o archivos. Seleccione la opción *Habilitar indexación* cuando esté realizando una búsqueda y restauración.

El catálogo indexado puede luego rastrear cada volumen y archivo de respaldo, haciendo que sus búsquedas sean rápidas y eficientes.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["Cómo restaurar los datos de ONTAP con la opción de  Restaurar"].



==== Puntos de conexión de vínculo privado y puntos de conexión de servicio de Azure

Normalmente, BlueXP Backup and Recovery establece un punto final privado con el proveedor de la nube para gestionar diversas tareas de protección. Esta versión incluye una configuración opcional que permite habilitar o deshabilitar la creación automática de un punto final privado por parte de BlueXP Backup and Recovery. Esto puede resultar útil si desea mayor control sobre el proceso de creación de puntos finales privados.

Puede habilitar o deshabilitar esta opción al habilitar la protección o iniciar el proceso de restauración.

Si deshabilita esta configuración, deberá crear manualmente el punto final privado para que la copia de seguridad y la recuperación de BlueXP funcionen correctamente. Sin una conectividad adecuada, es posible que no pueda realizar las tareas de copia de seguridad y recuperación correctamente.



==== Compatibilidad con SnapMirror para la resincronización en la nube en ONTAP S3

La versión anterior introdujo compatibilidad con SnapMirror to Cloud Resync (SM-C Resync). Esta función optimiza la protección de datos durante la migración de volúmenes en entornos NetApp. Esta versión añade compatibilidad con SM-C Resync en ONTAP S3, así como con otros proveedores compatibles con S3, como Wasabi y MinIO.



==== Traiga su propio cubo para StorageGRID

Al crear archivos de copia de seguridad en el almacenamiento de objetos para un entorno de trabajo, BlueXP Backup and Recovery crea, de forma predeterminada, el contenedor (bucket o cuenta de almacenamiento) para los archivos de copia de seguridad en la cuenta de almacenamiento de objetos configurada. Anteriormente, podía anular esta configuración y especificar su propio contenedor para Amazon S3, Azure Blob Storage y Google Cloud Storage. Con esta versión, ahora puede usar su propio contenedor de almacenamiento de objetos de StorageGRID.

Consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["Crea tu propio contenedor de almacenamiento de objetos"].



=== 13 de mayo de 2025

Esta versión de copia de seguridad y recuperación de BlueXP  incluye las siguientes actualizaciones.



==== SnapMirror a Cloud Resincronizcar para migraciones de volúmenes

La función de resincronización de SnapMirror a la nube optimiza la protección de datos y la continuidad durante las migraciones de volúmenes en entornos NetApp. Cuando se migra un volumen con la replicación lógica de SnapMirror (LRSE), desde una puesta en marcha de NetApp en las instalaciones a otra o a una solución basada en el cloud, como Cloud Volumes ONTAP o Cloud Volumes Service, SnapMirror a Cloud Resync garantiza que los backups existentes en el cloud permanecen intactos y operativos.

Esta función elimina la necesidad de una operación de nueva base que requiere mucho tiempo y requiere muchos recursos, lo que permite que las operaciones de backup continúen tras la migración. Esta función es muy útil en escenarios de migración de cargas de trabajo, compatible tanto con FlexVols como con FlexGroups y está disponible a partir de la versión 9.16.1 de ONTAP.

Al mantener la continuidad del backup entre entornos, SnapMirror a Cloud Resync mejora la eficiencia operativa y reduce la complejidad de la gestión de datos híbrida y multicloud.

Para obtener información detallada sobre cómo realizar la operación de resincronización, consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/task-migrate-volumes-snapmirror-cloud-resync.html["Migrar volúmenes mediante SnapMirror a la resincronización en el cloud"].



==== Compatibilidad con el almacén de objetos MinIO de terceros (vista previa)

El backup y la recuperación de datos de BlueXP  amplía ahora su compatibilidad con almacenes de objetos de terceros con un enfoque principal en MinIO. Esta nueva función de vista previa le permite aprovechar cualquier almacén de objetos compatible con S3 para satisfacer sus necesidades de backup y recuperación.

Con esta versión de vista previa, esperamos garantizar una sólida integración con almacenes de objetos de terceros antes de que se implemente toda la funcionalidad. Le animamos a explorar esta nueva capacidad y proporcionar comentarios para ayudar a mejorar el servicio.


IMPORTANT: Esta función no se debe utilizar en producción.

*Limitaciones del modo de vista previa*

Mientras esta función está en la vista previa, hay ciertas limitaciones:

* Traiga su propio depósito (BYOB) no es compatible.
* No se admite la activación de DataLock en la política.
* No se admite la activación del modo Archivado en la política.
* Solo se admiten entornos ONTAP en las instalaciones.
* No se admite MetroCluster.
* No se admiten las opciones para habilitar el cifrado a nivel de bloque.


*Empezar*

Para comenzar a utilizar esta función de vista previa, debe activar una marca en el conector BlueXP . A continuación, puede introducir los detalles de conexión de su almacén de objetos de terceros MinIO en el flujo de trabajo de protección seleccionando el almacén de objetos *Compatible con terceros* en la sección de copia de seguridad.

Para obtener instrucciones sobre cómo activar las funciones de vista preliminar, consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/task-preview-enable.html["Active las funciones de vista previa en las funciones de backup y recuperación de BlueXP"].



=== 16 de abril de 2025

Esta versión de copia de seguridad y recuperación de BlueXP  incluye las siguientes actualizaciones.



==== Mejoras en la interfaz de usuario

Esta versión mejora tu experiencia al simplificar la interfaz:

* La eliminación de la columna Agregado de las tablas de volúmenes, junto con las columnas Política de Snapshot, Política de backup y Política de replicación de la tabla Volumen de la consola V2, da como resultado un diseño más sencillo.
* La exclusión de los entornos de trabajo no activados de la lista desplegable hace que la interfaz esté menos desordenada, la navegación sea más eficiente y la carga sea más rápida.
* Mientras la clasificación en la columna Etiquetas está desactivada, puede ver las etiquetas, garantizando que la información importante permanezca fácilmente accesible.
* La eliminación de etiquetas en los iconos de protección contribuye a un aspecto más limpio y reduce el tiempo de carga.
* Durante el proceso de activación del entorno de trabajo, un cuadro de diálogo muestra un icono de carga para proporcionar información hasta que se complete el proceso de detección, lo que mejora la transparencia y la confianza en las operaciones del sistema.




==== Consola de volumen mejorado (vista previa)

Ahora, la consola de volúmenes se carga en menos de 10 segundos, lo que proporciona una interfaz mucho más rápida y eficiente. Esta versión de vista previa está disponible para seleccionar clientes, ofreciéndoles una vista previa de estas mejoras.



==== Soporte para almacén de objetos Wasabi de terceros (Preview)

El backup y la recuperación de BlueXP  ahora amplía su compatibilidad con almacenes de objetos de terceros con un enfoque principal en Wasabi. Esta nueva función de vista previa te permite aprovechar cualquier almacén de objetos compatible con S3 para satisfacer tus necesidades de backup y recuperación.



===== Empezar con Wasabi

Para empezar a utilizar almacenamiento de terceros como almacén de objetos, debe habilitar un indicador en Conector BlueXP . A continuación, puede introducir los detalles de conexión de su almacén de objetos de terceros e integrarlos en sus flujos de trabajo de backup y recuperación.

.Pasos
. SSH en su conector.
. Acceda al contenedor del servidor cbs de backup y recuperación de BlueXP :
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. Abra el `default.json` archivo dentro de la `config` carpeta a través de VIM o cualquier otro editor:
+
[listing]
----
vi default.json
----
. Modificar `allow-s3-compatible`: false a `allow-s3-compatible`: true.
. Guarde los cambios.
. Salga del contenedor.
. Reinicie el contenedor del servidor cbs de copia de seguridad y recuperación de BlueXP .


.Resultado
Cuando haya vuelto a ENCENDER el contenedor, abra la interfaz de usuario de backup y recuperación de BlueXP . Al iniciar un backup o editar una estrategia de backup, verá que el nuevo proveedor «compatible con S3» aparece en la lista con otros proveedores de backup como AWS, Microsoft Azure, Google Cloud, StorageGRID y ONTAP S3.



===== Limitaciones del modo de vista previa

Mientras esta función está en la vista preliminar, tenga en cuenta las siguientes limitaciones:

* Traiga su propio depósito (BYOB) no es compatible.
* No se admite la activación del bloqueo de datos en una política.
* No se admite la activación del modo Archivado en una política.
* Solo se admiten entornos ONTAP en las instalaciones.
* No se admite MetroCluster.
* No se admiten las opciones para habilitar el cifrado a nivel de bloque.


Durante esta vista previa, le animamos a explorar esta nueva función y proporcionar comentarios sobre la integración con almacenes de objetos de terceros antes de que se implemente toda la funcionalidad.



== Clasificación



=== 14 de julio de 2025



==== Versión 1,45

Esta versión de BlueXP classification incluye cambios de código que optimizan la utilización de recursos y:

.Flujo de trabajo mejorado para agregar recursos compartidos de archivos para escanear
Se ha simplificado el flujo de trabajo para agregar recursos compartidos de archivos a un grupo. El proceso también diferencia la compatibilidad con el protocolo CIFS según el tipo de autenticación (Kerberos o NTLM).

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-classification/task-scanning-file-shares.html["Analizar recursos compartidos de archivos"].

.Información mejorada del propietario del archivo
Ahora puede ver más información sobre los propietarios de los archivos capturados en la pestaña Investigación. Al visualizar los metadatos de un archivo en la pestaña Investigación, ubique al propietario del archivo y luego seleccione **Ver detalles** para ver el nombre de usuario, el correo electrónico y el nombre de la cuenta SAM. También puede ver otros elementos propiedad de este usuario. Esta función solo está disponible para entornos de trabajo con Active Directory.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Investigue los datos almacenados en su organización"].



=== 10 de junio de 2025



==== Versión 1,44

Esta versión de clasificación de BlueXP  incluye:

.Tiempos de actualización mejorados para el panel de Gobernanza
Se han mejorado los tiempos de actualización de los componentes individuales del panel de Gobernanza. La siguiente tabla muestra la frecuencia de actualización de cada componente.

[cols="1,1"]
|===
| Componente | Horarios de actualización 


| Antigüedad de los datos | 24 horas 


| Categorías | 24 horas 


| Descripción general de los datos | 5 minutos 


| Archivos duplicados | 2 horas 


| Tipos de archivo | 24 horas 


| Datos no comerciales | 2 horas 


| Abra permisos | 24 horas 


| Búsquedas guardadas | 2 horas 


| Datos confidenciales y permisos amplios | 24 horas 


| Tamaño de los datos | 24 horas 


| Datos obsoletos | 2 horas 


| Principales repositorios de datos por nivel de sensibilidad | 2 horas 
|===
Puede ver la hora de la última actualización y actualizar manualmente los componentes Archivos duplicados, Datos no comerciales, Búsquedas guardadas, Datos obsoletos y Repositorios de datos principales por nivel de sensibilidad. Para obtener más información sobre el panel de gobernanza, consulte link:https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["Ver detalles de gobierno sobre los datos almacenados en su organización"] .

.Mejoras de rendimiento y seguridad
Se han realizado mejoras para mejorar el rendimiento, el consumo de memoria y la seguridad de la clasificación BlueXP.

.Corrección de errores
Redis se ha actualizado para mejorar la fiabilidad de la clasificación de BlueXP. Esta clasificación ahora utiliza Elasticsearch para mejorar la precisión de los informes de recuento de archivos durante los análisis.



=== 12 de mayo de 2025



==== Versión 1,43

Esta versión de clasificación de BlueXP  incluye:

.Priorice las secuencias de clasificación
La clasificación BlueXP  permite priorizar las exploraciones de mapas y clasificaciones, además de las de sólo asignación, lo que permite seleccionar las exploraciones que se realizan primero. Se admite la priorización de las exploraciones de asignación y clasificación durante y antes de que comiencen las exploraciones. Si decide priorizar una exploración mientras está en curso, se priorizan tanto las secuencias de asignación como las de clasificación.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["Priorice las adquisiciones"].

.Soporte para las categorías de datos de información de identificación personal canadiense (PII)
Las exploraciones de clasificación BlueXP  identifican categorías de datos de PII canadienses. Estas categorías incluyen información bancaria, números de pasaporte, números de seguro social, números de licencia de conducir y números de tarjeta de salud para todas las provincias y territorios canadienses.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Categorías de datos personales"].

.Clasificación personalizada (vista previa)
La clasificación BlueXP  admite clasificaciones personalizadas para las exploraciones de mapas y clasificaciones. Con clasificaciones personalizadas, puede personalizar los escaneos BlueXP  para capturar datos específicos de su organización mediante expresiones regulares. Esta función se encuentra actualmente en la vista preliminar.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-classification/task-custom-classification.html["Agregar clasificaciones personalizadas"].

.Pestaña Búsquedas guardadas
Se ha cambiado el nombre de la pestaña **Políticas** link:https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["**Búsquedas guardadas**"]. La funcionalidad no cambia.

.Enviar eventos de escaneo a la línea de tiempo de BlueXP 
La clasificación BlueXP  admite el envío de eventos de clasificación (cuando se inicia una exploración y cuando finaliza) a la link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["Línea de tiempo de BlueXP"^].

.Actualizaciones de seguridad
* El paquete Keras ha sido actualizado, mitigando vulnerabilidades (BDSA-2025-0107 y BDSA-2025-1984).
* La configuración de contenedores de Docker se ha actualizado. El contenedor ya no tiene acceso a las interfaces de red del host para crear paquetes de red raw. Al reducir el acceso innecesario, la actualización mitiga los posibles riesgos de seguridad.


.Mejoras en el rendimiento
Se han implementado mejoras de código para reducir el uso de RAM y mejorar el rendimiento general de la clasificación de BlueXP .

.Corrección de errores
Se han solucionado los errores que provocaban el fallo de las exploraciones de StorageGRID, las opciones de filtro de la página Investigación no cargaban y la evaluación de detección de datos no se descargaba para evaluaciones de gran volumen.



=== 14 de abril de 2025



==== Versión 1,42

Esta versión de clasificación de BlueXP  incluye:

.Análisis masivo para entornos de trabajo
La clasificación BlueXP  admite operaciones masivas para entornos de trabajo. Puede optar por activar la asignación de exploraciones, activar la asignación y clasificación de exploraciones, desactivar exploraciones o crear una configuración personalizada en los volúmenes del entorno de trabajo. Si se realiza una selección para un volumen individual, se anula la selección masiva. Para realizar una operación masiva, navegue a la página **Configuración** y realice su selección.

.Descargue el informe de investigación localmente
La clasificación BlueXP  permite descargar informes de investigación de datos localmente para verlos en el explorador. Si selecciona la opción local, la investigación de datos solo está disponible en formato CSV y solo muestra las primeras 10.000 filas de datos.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#create-the-data-investigation-report["Investiga los datos almacenados en tu organización con la clasificación BlueXP"].



=== 10 de marzo de 2025



==== Versión 1,41

Esta versión de clasificación de BlueXP  incluye mejoras generales y correcciones de errores. También incluye:

.Estado de adquisición
La clasificación BlueXP  realiza un seguimiento del progreso en tiempo real de las exploraciones de asignación y clasificación _initial_ en un volumen. Las barras progresivas separadas realizan un seguimiento de las exploraciones de mapeo y clasificación, presentando un porcentaje del total de archivos escaneados. También puede pasar el ratón sobre una barra de progreso para ver el número de archivos escaneados y el total de archivos. El seguimiento del estado de sus escaneos crea una visión más profunda del progreso del escaneo, lo que le permite planificar mejor sus escaneos y comprender la asignación de recursos.

Para ver el estado de sus escaneos, vaya a **Configuración** en la clasificación BlueXP  y luego seleccione la **Configuración del entorno de trabajo**. El progreso se muestra en la línea para cada volumen.



=== 19 de febrero de 2025



==== Versión 1,40

Esta versión de clasificación de BlueXP  incluye las siguientes actualizaciones.

.Compatibilidad con RHEL 9,5
Esta versión es compatible con Red Hat Enterprise Linux v9,5 además de las versiones compatibles anteriormente. Esto se aplica a cualquier instalación manual en las instalaciones de la clasificación BlueXP , incluidas las puestas en marcha de sitios oscuros.

Los siguientes sistemas operativos requieren el uso del motor de contenedores Podman y requieren la versión de clasificación BlueXP  1,30 o superior: Red Hat Enterprise Linux versión 8,8, 8,10, 9,0, 9,1, 9,2, 9,3, 9,4 y 9,5.

.Priorice las exploraciones de sólo asignación
Al realizar exploraciones de sólo asignación, puede priorizar las exploraciones más importantes. Esta función ayuda cuando tiene muchos entornos de trabajo y desea garantizar que las exploraciones de alta prioridad se completen primero.

De forma predeterminada, las exploraciones se ponen en cola según el orden en el que se inician. Con la capacidad de priorizar las exploraciones, puede mover las exploraciones al frente de la cola. Se puede priorizar varias adquisiciones. La prioridad se designa en un orden de primero en entrar, primero en salir, lo que significa que la primera exploración que prioriza se mueve al frente de la cola; la segunda exploración que prioriza se convierte en la segunda en la cola, y así sucesivamente.

La prioridad se concede una vez. Las nuevas exploraciones automáticas de los datos de asignación se producen en el orden predeterminado.

La priorización está limitada alink:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["exploraciones de sólo asignación"^]; no está disponible para las exploraciones de mapas y clasificaciones.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["Priorice las adquisiciones"^].

.Vuelva a intentar todas las adquisiciones
La clasificación BlueXP  admite la capacidad de reintentar por lotes todos los análisis fallidos.

Puede volver a intentar escaneos en una operación por lotes con la función **Reintentar todo**. Si las exploraciones de clasificación fallan debido a un problema temporal, como una interrupción de la red, puede volver a intentar todas las exploraciones al mismo tiempo con un botón en lugar de volver a intentarlo individualmente. Las secuencias se pueden volver a intentar tantas veces como sea necesario.

Para volver a intentar todas las adquisiciones:

. En el menú de clasificación de BlueXP , selecciona *Configuración*.
. Para volver a intentar todos los escaneos fallidos, seleccione *Reintentar todos los escaneos*.


.Precisión mejorada del modelo de categorización
La precisión del modelo de aprendizaje automático link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["categorías predefinidas"]ha mejorado en un 11%.



=== 22 de enero de 2025



==== Versión 1,39

Esta versión de clasificación de BlueXP  actualiza el proceso de exportación del informe de investigación de datos. Esta actualización de exportación es útil para realizar análisis adicionales de sus datos, crear visualizaciones adicionales de los datos o compartir los resultados de su investigación de datos con otros.

Anteriormente, la exportación del informe de investigación de datos se limitaba a 10.000 filas. Con esta versión, el límite se ha eliminado para que pueda exportar todos sus datos. Este cambio le permite exportar más datos de sus informes de investigación de datos, lo que le proporciona más flexibilidad en el análisis de datos.

Puede elegir el entorno de trabajo, los volúmenes, la carpeta de destino y el formato JSON o CSV. El nombre de archivo exportado incluye una marca de tiempo para ayudarle a identificar cuándo se exportaron los datos.

Los entornos de trabajo compatibles incluyen:

* Cloud Volumes ONTAP
* FSX para ONTAP
* ONTAP
* Compartir grupo


La exportación de datos del informe de investigación de datos tiene las siguientes limitaciones:

* El número máximo de registros para descargar es de 500 millones por tipo (archivos, directorios y tablas)
* Se espera que un millón de registros tarde unos 35 minutos en exportarse.


Para obtener más información sobre la investigación de datos y el informe, consulte https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Investiga los datos almacenados en tu organización"].



=== 16 de diciembre de 2024



==== Versión 1,38

Esta versión de clasificación de BlueXP  incluye mejoras generales y correcciones de errores.



== Cloud Volumes ONTAP



=== 14 de julio de 2025



==== Soporte para proxy transparente

BlueXP ahora admite servidores proxy transparentes, además de las conexiones proxy explícitas existentes. Al crear o modificar el conector de BlueXP , puede configurar un servidor proxy transparente para gestionar de forma segura el tráfico de red hacia y desde Cloud Volumes ONTAP.

Para obtener más información sobre el uso de servidores proxy en Cloud Volumes ONTAP, consulte:

* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-aws.html#network-configurations-to-support-connector-proxy-servers["Configuraciones de red para soportar el proxy del conector en AWS"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/azure/reference-networking-azure.html#network-configurations-to-support-connector["Configuraciones de red para admitir el proxy del conector en Azure"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-gcp.html#network-configurations-to-support-connector-proxy["Configuraciones de red para admitir el proxy del conector en Google Cloud"^]




==== Nuevo tipo de máquina virtual compatible con Cloud Volumes ONTAP en Azure

A partir de Cloud Volumes ONTAP 9.13.1, L8s_v3 se admite como un tipo de máquina virtual en zonas de disponibilidad únicas y múltiples de Azure, tanto para implementaciones de pares de alta disponibilidad (HA) nuevas como existentes.

Para obtener más información, consulte https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configuraciones compatibles en Azure"^].



=== 29 de mayo de 2025



==== Despliegues de modo privado activados para Cloud Volumes ONTAP 9.15.1

Ahora puede poner en marcha Cloud Volumes ONTAP 9.15.1 en modo privado en AWS, Azure y Google Cloud. El modo privado está habilitado para las implementaciones de nodos únicos y de alta disponibilidad (HA) de Cloud Volumes ONTAP 9.15.1.

Para obtener más información sobre los despliegues en modo privado, consulte https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#restricted-mode["Obtenga más información sobre los modos de implementación de BlueXP"^].



=== 12 de mayo de 2025



==== Detección de implementaciones realizadas a través del mercado de Azure en BlueXP

BlueXP  ahora tiene la capacidad de detectar los sistemas Cloud Volumes ONTAP puestos en marcha directamente a través de Azure Marketplace. Esto significa que ahora puede añadir y gestionar estos sistemas como entornos de trabajo en BlueXP , al igual que cualquier otro sistema de Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploy-cvo-azure-mktplc.html["Ponga en marcha Cloud Volumes ONTAP desde Azure Marketplace"^]



==== Capacidad de organizar datos en niveles para inquilinos de Azure

Ahora puede habilitar la organización en niveles para un inquilino de Azure en una situación en la que el entorno de trabajo de Cloud Volumes ONTAP se crea mediante un inquilino y el conector BlueXP  se crea mediante otro. Mediante esta funcionalidad, puede utilizar el mismo conector para organizar datos en niveles para múltiples inquilinos de Azure.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html#requirements-to-tier-data-for-an-azure-tenant["Requisitos para organizar los datos en niveles para un inquilino de Azure"^]



== Cloud Volumes Service para Google Cloud



=== 9 de septiembre de 2020



==== Compatibilidad con Cloud Volumes Service para Google Cloud

Ahora puede gestionar Cloud Volumes Service para Google Cloud directamente desde BlueXP:

* Configurar y crear un entorno de trabajo
* Cree y gestione volúmenes NFSv3 y NFSv4.1 para clientes de Linux y UNIX
* Crear y gestionar volúmenes de SMB 3.x para clientes Windows
* Crear, eliminar y restaurar copias de Snapshot de volumen




== Copiar y sincronizar



=== 2 de febrero de 2025



==== Nuevo soporte de SO para el agente de datos

El agente de datos ahora es compatible con hosts que ejecutan Red Hat Enterprise 9,4, Ubuntu 23,04 y Ubuntu 24,04.

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["Vea los requisitos del host Linux"].



=== 27 de octubre de 2024



==== Corrección de errores

Actualizamos el servicio de copia y sincronización de BlueXP y el agente de datos para solucionar algunos errores. La nueva versión de Data Broker es 1,0.56.



=== 16 de septiembre de 2024



==== Corrección de errores

Actualizamos el servicio de copia y sincronización de BlueXP y el agente de datos para solucionar algunos errores. La nueva versión de Data Broker es 1,0.55.



== Asesor digital



=== 08 de mayo de 2025



==== Widget de AutoSupport

El widget AutoSupport se ha mejorado para incluir una ventana emergente que proporciona detalles sobre los sistemas que han dejado de enviar datos AutoSupport. Al habilitar AutoSupport se reducen los riesgos de tiempo de inactividad y se admite la gestión proactiva del estado del sistema.



==== Informe de contratos de soporte

El informe de contratos de soporte se ha mejorado para incluir el nuevo campo de indicador ASP/LSG. Este campo le permite filtrar e identificar los sistemas cubiertos por un partner de soporte autorizado, también conocido como certificado de servicios de ciclo de vida.



==== Panel de sostenibilidad

Ahora puede iniciar el panel de Sustainability utilizando el enlace incluido en la presentación de Sustainability.



=== 05 de marzo de 2025



==== Asesor de actualizaciones

* Con Disk Qualification Package (DQP), ahora puede actualizar automáticamente los controladores de disco y el firmware del dispositivo de almacenamiento según los criterios de estado y rendimiento predefinidos. Esto reduce los fallos potenciales y mejora la fiabilidad general del sistema.
* Se ha introducido la base de datos de zona horaria (DB) para mantener automáticamente la alineación del sistema con las últimas definiciones de zona horaria. Esto garantiza que las operaciones dependientes del tiempo continúen sin problemas incluso cuando las reglas de zona horaria cambien.




=== 12 de diciembre de 2024



==== Asesor de actualizaciones

Ahora puede ver el firmware de almacenamiento, el firmware de SP/BMC y el paquete autónomo de ransomware (ARP) que se recomiendan para una actualización. link:https://docs.netapp.com/us-en/active-iq/view-firmware-update-recommendations.html["Aprenda a ver las recomendaciones de actualización de firmware"].



== Cartera digital



=== 10 de marzo de 2025



==== Posibilidad de eliminar suscripciones

Ahora puede eliminar suscripciones de la cartera digital si ha cancelado su suscripción.



==== Ver la capacidad consumida para las suscripciones de Marketplace

Al visualizar las suscripciones PAYGO, ahora puede ver la capacidad consumida de la suscripción.



=== 10 de febrero de 2025

La cartera digital de BlueXP  se ha rediseñado para facilitar el uso y ahora proporciona gestión de licencias y suscripciones adicionales.



==== Nuevo panel de información general

La página de inicio de la cartera digital tiene un panel actualizado de tus licencias de NetApp y suscripciones de Marketplace, con la capacidad de profundizar en servicios específicos, tipos de licencias y acciones necesarias.



==== Configurando suscripciones a credenciales

Ahora, la cartera digital de BlueXP  le permite configurar sus suscripciones con las credenciales del proveedor. Normalmente, lo haces cuando te suscribes por primera vez a una suscripción del Marketplace o un contrato anual. El cambio anterior de las credenciales de la suscripción sólo se podía realizar en la página Credenciales.



==== Asociación de suscripciones a organizaciones

Ahora puede actualizar la organización a la que está asociada una suscripción directamente desde la cartera digital.



==== Gestión de licencias de Cloud Volumes ONTAP

Ahora administra las licencias de Cloud Volumes ONTAP a través de la página de inicio o la pestaña *Licencias directas*. Utilice la pestaña *Suscripciones de Marketplace* para ver la información de su suscripción.



=== 5 de marzo de 2024



==== Recuperación ante desastres de BlueXP

La cartera digital de BlueXP ahora te permite gestionar las licencias para la recuperación ante desastres de BlueXP. Es posible añadir licencias, actualizar licencias y ver detalles sobre la capacidad con licencia.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Descubre cómo gestionar las licencias para los servicios de datos de BlueXP"]



=== 30 de julio de 2023



==== Mejoras en los informes de uso

Hay disponibles varias mejoras en los informes de uso de Cloud Volumes ONTAP:

* La unidad TiB ahora se incluye en el nombre de las columnas.
* Ahora se incluye un nuevo campo _node(s)_ para los números de serie.
* Ahora se incluye una nueva columna _Workload Type_ en el informe Storage VMs usage.
* Los nombres de entornos de trabajo ahora se incluyen en los informes de uso de volúmenes y máquinas virtuales de almacenamiento.
* El tipo de volumen _file_ ahora está etiquetado como _Primary (Read/Write)_.
* El tipo de volumen _secondary_ ahora está etiquetado como _Secondary (DP)_.


Para obtener más información sobre los informes de uso, consulte https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Descargar informes de uso"].



== Recuperación tras siniestros



=== 14 de julio de 2025

Versión 4.2.5



==== Roles de usuario en la BlueXP disaster recovery

La BlueXP disaster recovery ahora emplea roles para gobernar el acceso que tiene cada usuario a funciones y acciones específicas.

El servicio utiliza los siguientes roles que son específicos para la BlueXP disaster recovery.

* *Administrador de recuperación ante desastres*: realiza cualquier acción en la BlueXP disaster recovery.
* *Administrador de conmutación por error de recuperación ante desastres*: realiza acciones de conmutación por error y migración en la BlueXP disaster recovery.
* *Administrador de aplicaciones de recuperación ante desastres*: crear y modificar planes de replicación e iniciar conmutaciones por error de prueba.
* *Visor de recuperación ante desastres*: ve información en la BlueXP disaster recovery, pero no puede realizar ninguna acción.


Si hace clic en el servicio de BlueXP disaster recovery y lo configura por primera vez, debe tener el permiso *SnapCenterAdmin* o tener el rol de *Administrador de la organización*.

Para obtener más información, consulte  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["Roles y permisos de usuario en la BlueXP disaster recovery"].

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso de BlueXP para todos los servicios"^].



==== Otras actualizaciones en la BlueXP disaster recovery

* Descubrimiento de red mejorado
* Mejoras de escalabilidad:
+
** Filtrado de los metadatos requeridos en lugar de todos los detalles
** Mejoras en el descubrimiento para recuperar y actualizar recursos de máquinas virtuales más rápidamente
** Optimización de la memoria y optimización del rendimiento para la recuperación y actualización de datos.
** Mejoras en la creación de clientes y la gestión de grupos de vCenter SDK


* Gestión de datos obsoletos en el próximo descubrimiento programado o manual:
+
** Cuando se elimina una máquina virtual en vCenter, la BlueXP disaster recovery ahora la elimina automáticamente del plan de replicación.
** Cuando se elimina un almacén de datos o una red en vCenter, la BlueXP disaster recovery ahora lo elimina del plan de replicación y del grupo de recursos.
** Cuando se elimina un clúster, un host o un centro de datos en vCenter, la BlueXP disaster recovery ahora lo elimina del plan de replicación y del grupo de recursos.


* Ahora puede acceder a la documentación de Swagger en el modo incógnito de su navegador. Puede acceder a ella desde la BlueXP disaster recovery, en la opción Configuración > Documentación de la API, o directamente en la siguiente URL en el modo incógnito de su navegador:  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Documentación de Swagger"^] .
* En algunas situaciones, tras una operación de recuperación, el iGroup se dejaba atrás una vez completada la operación. Esta actualización elimina el iGroup si está obsoleto.
* Si se utilizó el FQDN de NFS en el plan de replicación, la BlueXP disaster recovery ahora lo resuelve a una dirección IP. Esta actualización es útil si el FQDN no se puede resolver en el sitio de recuperación ante desastres.
* Mejoras en la alineación de la interfaz de usuario
* Mejoras en el registro para capturar los detalles de tamaño de vCenter después del descubrimiento exitoso




=== 30 de junio de 2025

Versión 4.2.4P2



==== Mejoras en el descubrimiento

Esta actualización mejora el proceso de descubrimiento, lo que reduce el tiempo necesario para realizarlo.



=== 23 de junio de 2025

Versión 4.2.4P1



==== Mejoras en el mapeo de subredes

Esta actualización mejora el cuadro de diálogo Agregar y editar asignación de subredes con una nueva función de búsqueda. Ahora puede encontrar subredes específicas rápidamente introduciendo términos de búsqueda, lo que facilita la gestión de asignaciones de subredes.



=== 9 de junio de 2025

Versión 4.2.4



==== Compatibilidad con la solución de contraseña de administrador local de Windows (LAPS)

La Solución de contraseña de administrador local de Windows (Windows LAPS) es una función de Windows que administra y realiza copias de seguridad automáticamente de la contraseña de una cuenta de administrador local en Active Directory.

Ahora puede seleccionar las opciones de mapeo de subredes y activar la opción LAPS proporcionando los detalles del controlador de dominio. Con esta opción, no necesita proporcionar una contraseña para cada máquina virtual.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"] .



== Sistemas E-Series



=== 12 de mayo de 2025



==== Se necesita el rol de acceso a BlueXP

Ahora necesita uno de los siguientes roles de acceso para ver, descubrir o administrar E-Series en BlueXP: administrador de la organización, administrador de carpeta o proyecto, administrador de almacenamiento o especialista en estado del sistema.  https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso de BlueXP."^]



=== 18 de septiembre de 2022



==== Compatibilidad con E-Series

Ahora puedes detectar tus sistemas E-Series directamente en BlueXP. El descubrimiento de sistemas E-Series le ofrece una visión completa de los datos en su multicloud híbrido.



== Eficiencia económica



=== 15 de mayo de 2024



==== Operaciones desactivadas

Algunas de las funciones de eficiencia económica de BlueXP  se han desactivado temporalmente:

* Renovación tecnológica
* Añadir capacidad




=== 14 de marzo de 2024



==== Opciones de actualización tecnológica

Si tienes activos implementados y quieres determinar si es necesario actualizar una tecnología, puedes utilizar las opciones de actualización de la tecnología de eficiencia económica de BlueXP. Puede revisar una breve evaluación de sus cargas de trabajo actuales y recibir recomendaciones, o bien si envió registros de AutoSupport a NetApp en los últimos 90 días, el servicio ahora puede proporcionar una simulación de cargas de trabajo para ver el rendimiento de las cargas de trabajo en hardware nuevo.

También puede agregar una carga de trabajo y excluir las cargas de trabajo existentes de la simulación.

Anteriormente, solo podía realizar una evaluación de sus activos e identificar si se recomienda una actualización tecnológica.

Ahora la función forma parte de la opción Tech Refresh de la barra de navegación izquierda.

Obtenga más información sobre el https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["Evaluar una actualización tecnológica"].



=== 08 de noviembre de 2023



==== Renovación tecnológica

Esta versión de la eficiencia económica de BlueXP incluye una nueva opción para realizar una evaluación de sus activos e identificar si se recomienda una actualización tecnológica. El servicio incluye una nueva opción de actualización tecnológica en la navegación izquierda, nuevas páginas en las que puede realizar una evaluación de sus activos y cargas de trabajo actuales, y un informe que le ofrece recomendaciones.



== Almacenamiento en caché en el edge

El servicio de almacenamiento en caché perimetral de BlueXP  se eliminó el 7 de agosto de 2024.



== Google Cloud Storage



=== 10 de julio de 2023



==== Capacidad para añadir nuevos bloques y gestionar bloques existentes desde BlueXP

Has tenido la capacidad de ver buckets de almacenamiento de Google Cloud en BlueXP Canvas durante bastante tiempo. Ahora puede agregar nuevos cubos y cambiar las propiedades de los cubos existentes directamente desde BlueXP . https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["Descubre cómo añadir nuevos buckets de Google Cloud Storage"].



== Keystone



=== 19 de junio de 2025



==== Panel de control de Keystone en BlueXP

Ahora puede acceder al panel de control de Keystone directamente desde BlueXP. Esta integración le ofrece un único lugar para supervisar, gestionar y realizar un seguimiento de todas sus suscripciones de Keystone, junto con sus demás servicios de NetApp.

Con el panel de control de Keystone en BlueXP, puedes:

* Vea todos los detalles de su suscripción, el uso de capacidad y los activos en un solo lugar.
* Administre fácilmente sus suscripciones y solicite cambios a medida que evolucionen sus necesidades.
* Manténgase actualizado con la información más reciente para su entorno de almacenamiento.


Para comenzar, vaya a *Almacenamiento > Keystone* en el menú de navegación izquierdo de BlueXP. Para obtener más información, consulte link:https://docs.netapp.com/us-en/keystone-staas/integrations/dashboard-overview.html["Información general del panel de Keystone"].



== Kubernetes

El 7 de agosto de 2024 se eliminó la compatibilidad para detectar y gestionar clústeres de Kubernetes.



== Informes de migración

El servicio de informes de migración de BlueXP  se eliminó el 7 de agosto de 2024.



== Clústeres de ONTAP en las instalaciones



=== 12 de mayo de 2025



==== Se necesita el rol de acceso a BlueXP

Ahora necesita uno de los siguientes roles de acceso para ver, descubrir o administrar clústeres de ONTAP locales: administrador de la organización, administrador de carpeta o proyecto, administrador de almacenamiento o especialista en estado del sistema. link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso de BlueXP."^]



=== 26 de noviembre de 2024



==== Compatibilidad con sistemas ASA R2 con modo privado

Ahora puede descubrir los sistemas NetApp ASA R2 al utilizar BlueXP  en modo privado. Esta asistencia está disponible a partir de la versión 3.9.46 del modo privado de BlueXP .

* https://docs.netapp.com/us-en/asa-r2/index.html["Obtenga más información sobre los sistemas R2 de ASA"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"^]




=== 7 de octubre de 2024



==== Compatibilidad con los sistemas ASA R2

Ahora puede detectar los sistemas NetApp ASA R2 en BlueXP  cuando se utiliza BlueXP  en modo estándar o restringido. Después de detectar un sistema NetApp ASA R2 y abrir el entorno de trabajo, se le pasará directamente a System Manager.

No hay otras opciones de gestión disponibles con los sistemas ASA R2. No se puede utilizar la vista estándar y no se pueden habilitar los servicios de BlueXP.

La detección de sistemas ASA R2 no es compatible cuando se usa BlueXP  en el modo privado.

* https://docs.netapp.com/us-en/asa-r2/index.html["Obtenga más información sobre los sistemas R2 de ASA"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"^]




== Resiliencia operativa



=== 02 de abril de 2023



==== Servicio de resiliencia operativa de BlueXP

Mediante el nuevo servicio de resiliencia operativa de BlueXP y sus sugerencias automatizadas para la corrección de los riesgos operativos TECNOLÓGICOS, puedes implementar soluciones sugeridas antes de que se produzca una interrupción o un fallo.

La resiliencia operativa es un servicio que le ayuda a analizar las alertas y los eventos para mantener el estado, el tiempo de actividad y el rendimiento de los servicios y las soluciones.

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["Obtenga más información sobre la resiliencia operativa de BlueXP"].



== Protección contra ransomware



=== 15 de julio de 2025



==== Soporte de carga de trabajo SAN

Esta versión incluye compatibilidad con cargas de trabajo SAN en la BlueXP ransomware protection. Ahora puede proteger cargas de trabajo SAN, además de cargas de trabajo NFS y CIFS.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["Requisitos previos de protección contra ransomware de BlueXP"].



==== Protección mejorada de la carga de trabajo

Esta versión incluye un flujo de trabajo mejorado para proteger cargas de trabajo con o sin protección de datos. Si utiliza otras herramientas de protección de datos de NetApp , como SnapCenter o BlueXP backup and recovery , para sus snapshots o backups, la BlueXP ransomware protection las detecta y le permite mantener las políticas que las rigen. Con esta versión, puede sustituir dichas políticas por las de BlueXP ransomware protection o seguir utilizando las existentes.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["Proteja las cargas de trabajo"] .



==== Notificaciones por correo electrónico

Si la BlueXP ransomware protection detecta un posible ataque, se mostrará una notificación en las Notificaciones de BlueXP y se enviará un correo electrónico a la dirección configurada. El servicio también generará una instantánea inmediatamente.

En este punto, debe ver el correo electrónico, que enumera la gravedad y los recursos afectados y observar el riesgo potencial en la pestaña *Alertas* de BlueXP ransomware protection .

Si configuró una gestión de eventos y seguridad (SIEM) en la BlueXP ransomware protection, el servicio envía detalles de alerta a su sistema SIEM.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Gestionar alertas de ransomware detectadas"] .



=== 9 de junio de 2025



==== Actualizaciones de la página de destino

Esta versión incluye actualizaciones a la página de inicio de la protección contra ransomware BlueXP que facilita el inicio de la prueba gratuita y el descubrimiento.



==== Actualizaciones de simulacros de preparación

Anteriormente, se podía ejecutar un simulacro de preparación contra ransomware simulando un ataque en una nueva carga de trabajo de muestra. Con esta función, se puede investigar el ataque simulado y recuperar la carga de trabajo. Utilice esta función para probar las notificaciones de alerta, la respuesta y la recuperación. Ejecute y programe estos simulacros con la frecuencia que necesite.

Con esta versión, puede usar un nuevo botón en el Panel de protección contra ransomware de BlueXP para ejecutar un simulacro de preparación para ransomware en una carga de trabajo de prueba, lo que le facilita simular ataques de ransomware, investigar su impacto y recuperar cargas de trabajo de manera eficiente, todo dentro de un entorno controlado.

Ahora puede ejecutar simulacros de preparación en cargas de trabajo CIFS (SMB) además de en cargas de trabajo NFS.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Haz un simulacro de preparación para los ataques de ransomware"] .



==== Habilitar actualizaciones de clasificación de BlueXP

Antes de usar la clasificación de BlueXP  dentro del servicio de protección contra ransomware de BlueXP , debe habilitar la clasificación BlueXP  para analizar sus datos. La clasificación de datos le ayuda a encontrar información de identificación personal (PII), lo que puede aumentar los riesgos de seguridad.

Puede implementar la clasificación de BlueXP en una carga de trabajo de recursos compartidos de archivos desde la protección contra ransomware de BlueXP. En la columna *Exposición de privacidad*, seleccione la opción *Identificar exposición*. Si ha habilitado el servicio de clasificación, esta acción identifica la exposición. De lo contrario, con esta versión, un cuadro de diálogo presenta la opción para implementar la clasificación de BlueXP. Seleccione *Implementar* para ir a la página principal del servicio de clasificación de BlueXP, donde podrá implementarlo. W

Para más detalles, consulte  https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html["Pon en marcha la clasificación de BlueXP en el cloud"^] y para utilizar el servicio dentro de la protección contra ransomware BlueXP, consulte  https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect-classify.html["Escanee para obtener información de identificación personal con la clasificación BlueXP"] .



=== 13 de mayo de 2025



==== Informes de entornos de trabajo no compatibles en la protección frente al ransomware de BlueXP

Durante el flujo de trabajo de detección, la protección frente al ransomware de BlueXP  informa de más detalles al pasar el ratón por cargas de trabajo compatibles o incompatibles. Esto te ayudará a comprender por qué el servicio de protección frente a ransomware de BlueXP  no se detectan algunas de tus cargas de trabajo.

Hay muchas razones por las que el servicio no soporta un entorno de trabajo, por ejemplo, la versión de ONTAP en su entorno de trabajo podría estar por debajo de la versión requerida. Cuando pasa el ratón sobre un entorno de trabajo no admitido, una información sobre herramientas muestra el motivo.

Es posible ver los entornos de trabajo no compatibles durante la detección inicial, donde también se pueden descargar los resultados. También puede ver los resultados de la detección desde la opción *Detección de carga de trabajo* en la página Configuración.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Detecta cargas de trabajo en la protección frente al ransomware de BlueXP"] .



=== 29 de abril de 2025



==== Compatibilidad con Amazon FSX para ONTAP de NetApp

Esta versión es compatible con Amazon FSx para NetApp ONTAP. Esta función te ayuda a proteger las cargas de trabajo de FSx para ONTAP con la protección frente a ransomware de BlueXP .

FSX para ONTAP es un servicio totalmente gestionado que proporciona la potencia del almacenamiento de NetApp ONTAP en la nube. Ofrece las mismas funciones, rendimiento y funcionalidades administrativas que utiliza en las instalaciones con la agilidad y la escalabilidad de un servicio nativo de AWS.

Se han realizado los siguientes cambios en el flujo de trabajo de protección frente a ransomware de BlueXP :

* La detección incluye cargas de trabajo en FSx para entornos de trabajo de ONTAP 9,15.
* La pestaña Protección muestra las cargas de trabajo en FSx para entornos ONTAP. En este entorno, debes ejecutar operaciones de backup mediante el servicio de backup de FSx para ONTAP. Puede restaurar estas cargas de trabajo mediante snapshots de protección frente al ransomware de BlueXP .
+

TIP: Las políticas de backup para una carga de trabajo que se ejecuta en FSx para ONTAP no se pueden establecer en BlueXP . Las políticas de backup existentes establecidas en Amazon FSx para NetApp ONTAP no cambian.

* Los incidentes de alertas muestran el nuevo entorno de trabajo de FSx para ONTAP.


Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["Obtén más información sobre los entornos de trabajo y la protección frente al ransomware de BlueXP"] .

Para obtener más información sobre las opciones admitidas, consulte la https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html["Limitaciones de protección contra ransomware de BlueXP"].



==== Se necesita el rol de acceso a BlueXP

Ahora necesita uno de los siguientes roles de acceso para ver, descubrir o administrar la protección contra ransomware de BlueXP: administrador de la organización, administrador de carpeta o proyecto, administrador de protección contra ransomware o visor de protección contra ransomware.

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso de BlueXP para todos los servicios"^].



=== 14 de abril de 2025



==== Informes de detalle de preparación

Con este lanzamiento, puede revisar los informes simulacros de preparación para los ataques de ransomware. Un ejercicio de preparación le permite simular un ataque de ransomware en una carga de trabajo de muestra recién creada. A continuación, investigue el ataque simulado y recupere la carga de trabajo de muestra. Esta función te ayuda a saber que estás preparado en caso de un ataque real de ransomware mediante la prueba de los procesos de notificación de alertas, respuesta y recuperación.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Haz un simulacro de preparación para los ataques de ransomware"] .



==== Nuevos roles y permisos de control de acceso basado en roles

Antes, podrías asignar roles y permisos a los usuarios en función de sus responsabilidades, lo que te ayudaba a gestionar el acceso de los usuarios a la protección frente al ransomware de BlueXP . Con esta versión, hay dos roles nuevos específicos de la protección contra ransomware de BlueXP  con permisos actualizados. Los nuevos roles son los siguientes:

* Administrador de protección frente a ransomware
* Visor de protección contra ransomware


Para obtener más información sobre los permisos, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["Acceso a funciones basado en roles de protección frente al ransomware de BlueXP"] .



==== Mejoras de pago

Esta versión incluye varias mejoras en el proceso de pago.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["Configurar opciones de licencia y pago"] .



== Reparación

El servicio de corrección de BlueXP se eliminó el 22 de abril de 2024.



== Replicación



=== 18 de septiembre de 2022



==== FSX para ONTAP a Cloud Volumes ONTAP

Ahora puede replicar datos de un sistema de archivos Amazon FSX para ONTAP en Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Aprenda a configurar la replicación de datos"].



=== 31 de julio de 2022



==== FSX para ONTAP como origen de datos

Ahora puede replicar datos de un sistema de archivos Amazon FSX para ONTAP en los siguientes destinos:

* Amazon FSX para ONTAP
* Clúster de ONTAP en las instalaciones


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Aprenda a configurar la replicación de datos"].



=== 2 de septiembre de 2021



==== Compatibilidad con Amazon FSX para ONTAP

Ahora puede replicar datos desde un sistema Cloud Volumes ONTAP o un clúster de ONTAP en las instalaciones en un sistema de archivos Amazon FSX para ONTAP.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Aprenda a configurar la replicación de datos"].



== Actualizaciones de software



=== 12 de mayo de 2025



==== Se necesita el rol de acceso a BlueXP

Ahora necesita uno de los siguientes roles de acceso para instalar actualizaciones de software: *Administrador de la organización*, *Administrador de carpetas o proyectos*, *Administrador de almacenamiento*, *Visor de almacenamiento* o *Especialista en estado de almacenamiento*. Los usuarios con el rol de Visor de almacenamiento tienen varios permisos relacionados con las actualizaciones de software, pero no pueden instalarlas. link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso de BlueXP."^]



=== 02 de abril de 2025



==== Reducción de riesgos

En la sección de resumen de las actualizaciones de software de BlueXP , ahora puede ver el número total de riesgos que se pueden mitigar mediante la actualización del sistema operativo. Esto permite a los usuarios evaluar las mejoras de seguridad y estabilidad en su base de instalación.



=== 07 de agosto de 2024



==== Actualización de ONTAP

El servicio de actualizaciones de software de BlueXP  ofrece a los usuarios una experiencia de actualización fluida al mitigar los riesgos y garantizar que los clientes puedan sacar el máximo partido a las funciones de ONTAP.

Más información sobre link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["Actualizaciones de software de BlueXP"].



== StorageGRID



=== 12 de mayo de 2025



==== Se necesitan roles de acceso a BlueXP

Ahora necesita uno de los siguientes roles de acceso para ver, descubrir o administrar StorageGRID en BlueXP: *Administrador de la organización*, *Administrador de carpeta o proyecto*, *Administrador de almacenamiento* o *Especialista en estado de almacenamiento*. link:https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso de BlueXP."^]



=== 7 de agosto de 2024



==== Nueva vista avanzada

A partir de StorageGRID 11,8, puede utilizar la conocida interfaz de Grid Manager para gestionar su sistema StorageGRID desde BlueXP .

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["Aprenda a administrar StorageGRID con la vista avanzada"].



==== Capacidad para revisar y aprobar el certificado de interfaz de gestión de StorageGRID

Ahora puede revisar y aprobar un certificado de interfaz de gestión de StorageGRID al detectar el sistema StorageGRID de BlueXP . También se puede revisar y aprobar el último certificado de interfaz de gestión de StorageGRID en una cuadrícula detectada.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Aprenda a revisar y aprobar el certificado de servidor durante la detección del sistema."]



=== 18 de septiembre de 2022



==== Compatibilidad con StorageGRID

Ahora puede descubrir sus sistemas StorageGRID directamente desde BlueXP. El descubrimiento de StorageGRID le ofrece una visión completa de los datos en su multicloud híbrido.



== Organización en niveles



=== 9 de agosto de 2023



==== Utilice un prefijo personalizado para el nombre del depósito

Anteriormente, era necesario utilizar el prefijo predeterminado «fabric-pool» al definir el nombre del bucket, por ejemplo, _fabric-pool-bucket1_. Ahora puede utilizar un prefijo personalizado al asignar un nombre a su cubo. Esta funcionalidad solo está disponible cuando se organizan los datos en niveles en Amazon S3. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["Leer más"].



==== Busca un clúster en todos los conectores de BlueXP

Si utiliza varios conectores para gestionar todos los sistemas de almacenamiento del entorno, algunos clústeres en los que desea implementar la organización en niveles pueden estar en conectores diferentes. Si no estás seguro de qué Connector gestiona un determinado clúster, puedes buscar en todos los conectores mediante la organización en niveles de BlueXP. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["Leer más"].



=== 4 de julio de 2023



==== Ajuste el ancho de banda para transferir datos inactivos

Al activar la organización en niveles de BlueXP, ONTAP puede utilizar una cantidad ilimitada de ancho de banda de red para transferir los datos inactivos de los volúmenes del clúster al almacenamiento de objetos. Si observa que el tráfico por niveles afecta a las cargas de trabajo normales de usuario, puede limitar la cantidad de ancho de banda que se puede utilizar durante la transferencia. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["Leer más"].



==== Evento de organización en niveles que se muestra en el Centro de notificaciones

El evento de organización en niveles «Almacenar los datos adicionales del clúster <name> en el almacenamiento de objetos para aumentar la eficiencia del almacenamiento» aparece ahora como una notificación cuando un clúster está organizando en niveles menos del 20 % de sus datos inactivos, incluidos los clústeres que organizan en niveles ningún dato.

Esta notificación es una «recomendación» que pretende hacer que sus sistemas sean más eficientes y ahorrar costes de almacenamiento. Proporciona un enlace al https://bluexp.netapp.com/cloud-tiering-service-tco["Calculadora de ahorro y coste total de propiedad de la organización en niveles de BlueXP"^] para ayudarle a calcular el ahorro de costes.



=== 3 de abril de 2023



==== Se ha eliminado la pestaña de licencias

La pestaña Licencias se ha eliminado de la interfaz de organización en niveles de BlueXP. Ahora, se accede a todas las licencias de suscripciones de pago por uso (PAYGO) desde la consola de organización en niveles de BlueXP en las instalaciones. También hay un enlace desde esa página a la cartera digital de BlueXP para que puedas ver y gestionar cualquier producto con tus propias licencias (BYOL) en la organización en niveles de BlueXP.



==== Se ha cambiado el nombre de las pestañas de organización en niveles y se han actualizado

Se ha cambiado el nombre de la pestaña «Consola de clústeres» a «Clusters» y la pestaña «On-Prem Overview» se ha cambiado a «On-premises Dashboard». Estas páginas han añadido información que le ayudará a evaluar si puede optimizar el espacio de almacenamiento con una configuración adicional de organización en niveles.



== Almacenamiento en caché de volúmenes



=== 04 de junio de 2023



==== Almacenamiento en caché de volúmenes

El almacenamiento en caché de volúmenes, una función del software ONTAP 9, es una funcionalidad de almacenamiento en caché remoto que simplifica la distribución de archivos, reduce la latencia WAN al acercar los recursos a dónde están los usuarios y los recursos informáticos y reduce los costes de ancho de banda WAN. El almacenamiento en caché de volúmenes proporciona un volumen persistente y editable en un lugar remoto. Puede usar el almacenamiento en caché de volúmenes de BlueXP para acelerar el acceso a los datos o para descargar el tráfico de volúmenes con un acceso frecuente. Los volúmenes de caché son ideales para las cargas de trabajo de lectura intensiva, especialmente cuando los clientes necesitan acceder a los mismos datos de manera repetida.

Con el almacenamiento en caché de volúmenes de BlueXP, dispones de capacidades de almacenamiento en caché para la nube, específicamente para Amazon FSx para NetApp ONTAP, Cloud Volumes ONTAP y on-premises como entornos de trabajo.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["Obtén más información sobre el almacenamiento en caché de volúmenes de BlueXP"].



== Fábrica de cargas de trabajo



=== 29 de junio de 2025



==== Actualización de permisos para bases de datos

El siguiente permiso ahora está disponible en modo de solo lectura para bases de datos:  `cloudwatch:GetMetricData` .

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Log de cambios de referencia de permisos"]



==== Compatibilidad con el servicio de notificación de fábrica de carga de trabajo de BlueXP

El servicio de notificaciones de la fábrica de cargas de trabajo de BlueXP permite que esta envíe notificaciones al servicio de alertas de BlueXP o a un tema de Amazon SNS. Las notificaciones enviadas a las alertas de BlueXP aparecen en el panel de alertas de BlueXP. Cuando la fábrica de cargas de trabajo publica notificaciones en un tema de Amazon SNS, los suscriptores del tema (como usuarios u otras aplicaciones) reciben las notificaciones en los endpoints configurados para el tema (como correos electrónicos o mensajes SMS).

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurar las notificaciones de fábrica de la carga de trabajo de BlueXP"]



=== 04 de mayo de 2025



==== Soporte autocompleto de CloudShell

Al utilizar CloudShell de fábrica de carga de trabajo de BlueXP , puede comenzar a escribir un comando y presionar la tecla TAB para ver las opciones disponibles. Si existen múltiples posibilidades, la CLI mostrará una lista de sugerencias. Esta función mejora la productividad al minimizar los errores y acelerar la ejecución de comandos.



==== Terminología de permisos actualizada

La interfaz de usuario y la documentación de la fábrica de carga de trabajo ahora usan "solo lectura" para referirse a los permisos de lectura y "lectura/escritura" para referirse a los permisos de automatización.



=== 30 de marzo de 2025



==== CloudShell informa de respuestas de errores generadas por IA para comandos de la CLI de ONTAP

Al usar CloudShell, cada vez que emita un comando de la CLI de ONTAP y se produce un error, puede obtener respuestas de error generadas por IA que incluyen una descripción del fallo, la causa del fallo y una resolución detallada.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Usar CloudShell"]



==== iam:SimulatePermissionPolicy actualización de permisos

Ahora puede administrar `iam:SimulatePrincipalPolicy` el permiso desde la consola de fábrica de cargas de trabajo cuando agrega credenciales de cuenta de AWS adicionales o agrega una nueva capacidad de carga de trabajo, como la carga de trabajo de GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Log de cambios de referencia de permisos"]



=== 02 de febrero de 2025



==== CloudShell disponible en la consola de fábrica de cargas de trabajo de BlueXP

CloudShell está disponible desde cualquier lugar de la consola de fábrica de cargas de trabajo de BlueXP . CloudShell le permite usar las credenciales de AWS y ONTAP que ha proporcionado en su cuenta de BlueXP  y ejecutar comandos de la CLI de AWS o comandos de la CLI de ONTAP en un entorno similar al shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Usar CloudShell"]



==== Actualización de permisos para bases de datos

El siguiente permiso ahora está disponible en el modo _READ_ para bases de datos `iam:SimulatePrincipalPolicy`: .

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Log de cambios de referencia de permisos"]
