= Conector 3.9.32
:allow-uri-read: 




=== Conector 3.9.32

* Ahora puedes usar la API del servicio de auditoría de BlueXP para exportar registros de auditoría.
+
El servicio de auditoría registra información sobre las operaciones realizadas por los servicios de BlueXP. Esto incluye espacios de trabajo, conectores utilizados y otros datos de telemetría. Puede utilizar estos datos para determinar qué acciones se realizaron, quién las realizó y cuándo ocurrieron.

+
https://docs.netapp.com/us-en/bluexp-automation/audit/overview.html["Obtenga más información sobre el uso de la API del servicio de auditoría"^]

+
Tenga en cuenta que también se puede acceder a este enlace desde la interfaz de usuario de BlueXP en la página Timeline.

* Esta versión del conector también incluye mejoras de Cloud Volumes ONTAP y mejoras del clúster de ONTAP en las instalaciones.
+
** https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#30-july-2023["Obtenga información acerca de las mejoras de Cloud Volumes ONTAP"^]
** https://docs.netapp.com/us-en/bluexp-ontap-onprem/whats-new.html#30-july-2023["Obtenga información acerca de las mejoras del clúster en las instalaciones de ONTAP"^]



